/*
*/

//modern breeds - need to sort them by rarity for calculations 
//possible substring issues - lace/laced, marble/marbled, mist/mistral 
const rarities ={"plentiful": ["Fae","Guardian","Mirror","Tundra", "Basic"],

  "common": ["Pearlcatcher","Ridgeback","Snapper","Spiral",
        "Checkers", "Clown", "Fade", "Falcon", "Laced", "Leopard", "Piebald", "Savanna", "Speckle", "Swirl", "Tapir", "Tiger", "Varnish", "Caterpillar", "Spool", "Wrought", "Marble", "Rabicano", "Arapaima", "Shaggy", "Radio", 
        "Blend", "Chess", "Clouded", "Edged", "Eye Spots", "Freckle", "Lacquer", "Paint", "Peregrine", "Safari", "Striation", "Stripes", "Marbled", "Larvae", "Spire", "Thread", "Mottle", "Roan", "Arowana", "Streak", "Signal", 
        "Contour", "Darts", "Peacock", "Points", "Thylacine", "Underbelly", "Kumo", "Braids", "Fangs", "Chitin", "Terracotta", "Topcoat", "Trimmings", "Quagga", "Wool", "Shardflank", "Barnacle"],
        
  "uncommon": ["Bogsneak","Obelisk","Fathom","Skydancer", 
         "Bar", "Boa", "Cherub", "Chorus", "Cinder", "Flaunt", "Giraffe", "Jaguar", "Jupiter", "Lionfish", "Mosaic", "Ragged", "Ribbon", "Ripple", "Sphinxmoth", "Vipera", "Mochlus", "Rattlesnake", "Chevron", "Criculaworm", "Faire", "Ink", "Strike", "Caiman", "Splatter", "Wolf", "Bright", "Shell", "Patina", 
         "Blaze", "Breakup", "Choir", "Current", "Daub", "Eel", "Flair", "Hawkmoth", "Hex", "Hypnotic", "Noxtide", "Rosette", "Saddle", "Saturn", "Seraph", "Tear", "Diamondback", "Riopa", "Arrow", "Carousel", "Dye", "Silkspot", "Coil", "Croc", "Drip", "Pack", "Vivid", "Web", "Oxidize", 
         "Crackle", "Gecko", "Gembond", "Ghost", "Lace", "Okapi", "Ringlets", "Runes", "Smoke", "Sparkle", "Spines", "Thorns", "Fishbone", "Stinger", "Whiskers", "Crest", "Paradise", "Willow", "Antlers", "Jellyfish", "Rift", "Sunsail", "Wintercoat", "Beard", "Plating", "Pufferfish", "Agate", "Rooster"],

  "limited": ["Nocturne","Imperial", 
        "Boulder", "Chrysocolla", "Fern", "Ground", "Love", "Orb", "Pinstripe", "Poison", "Python", "Sailfish", "Skink", "Slime", "Soil", "Stitched", "Tide", "Diamond", "Candy", "Candycane", "Arc", "Display", "Papillon", "Phantom", "Octopus", "Crosshatch", 
        "Affection", "Fissure", "Foam", "Loam", "Myrid", "Paisley", "Patchwork", "Sludge", "Spinner", "Toxin", "Trail", "Weaver", "Spade", "Icing", "Marlin", "Malachite", "Sugarplum", "Loop", "Parade", "Swallowtail", "Spirit", "Rings", "Hatch", 
        "Capsule", "Firebreather", "Firefly", "Flecks", "Keel", "Magpie", "Polkadot", "Scales", "Smirch", "Veined", "Blossom", "Carnivore", "Flameforger", "Mucous", "Brightshine", "Gliders", "Squiggle", "Coral", "Flames", "Topscale",
        "Polypore", "Riot", "Rockbreaker", "Skeletal", "Thundercrack", "Angler", "Crystalline", "Flutter", "Branches"," Mandibles", "Mistral", "Porcupine", "Starfall", "Trickmurk", "Batty", "Greenskeeper", "Skuttle", "Warrior", "Wavecrest", "Dewlap", "Pachy",
        "Eclosion", "Nudibranch", "Scorpion", "Weathered", "Shark", "Beetle", "Moss", "Sweet", "Tusked", "Yarn", "Hornet", "Featherbeard", "Porcelain", "Webmane"],

  "rare": ["Coatl","Wildclaw",
       "Crystal", "Harlequin", "Iridescent", "Metallic", "Petals", "Petrified", "Pharaoh", "Starmap", "Wasp", "Wicker", "Twinkle", "Throne", "Dimension", "Glow", "Glass",
       "Alloy", "Bee", "Butterfly", "Constellation", "Facet", "Jester", "Lode", "Sarcophagus", "Shimmer", "Flicker", "Woven", "Crown", "Chalice", "Lumen", "Warp", 
       "Circuit", "Eclipse", "Filigree", "Glimmer", "Glowtail", "Koi", "Opal", "Soap", "Stained", "Wish", "Augment", "Fans", "Frills", "Jewels", "Medusa", "Ornaments", "Spores", "Diaphanous", "Monarch", "Sailfin", "Tentacles", "Space",
      "Plumage", "Wraith", "Glitch", "Deco", "Mist", "Spectre", "Gnarlhorns", "Veil", "Harp", "Pinions", "Remora", "Mop", "Belfry", "Candlelight", "Overgrow"]};


const moderns = {"Fae": "1", "Guardian": "2", "Mirror": "3", "Pearlcatcher": "4", "Ridgeback": "5", "Tundra": "6", "Spiral": "7", "Imperial": "8", "Snapper": "9", "Wildclaw": "10", "Nocturne": "11", "Coatl": "12", "Skydancer": "13", 
        "Bogsneak": "14", "Obelisk": "15", "Fathom": "16"}
//ancient breeds 
const ancients = {"Gaoler": "17","Banescale": "18","Veilspun": "19","Aberration": "20","Undertide": "21","Aether": "22","Sandsurge": "23","Auraboa": "24","Dusthide": "25","Everlux": "26","Cirrus": "27","Thorntail": "29","Vigil": "28"};

//primary genes - sorted by modern and each ancient breed for easier insertions 
const primaryGenes ={"Modern": [{value: "6", desc:"Bar"},{value: "0", desc:"Basic"},{value: "232", desc:"Boa"},{value: "110", desc:"Boulder"}, 
{value: "412", desc:"Checkers"},{value: "10", desc:"Cherub"},{value: "337", desc:"Chorus"},{value: "237", desc:"Chrysocolla"}, 
{value: "213", desc:"Cinder"},{value: "3", desc:"Clown"},{value: "7", desc:"Crystal"},{value: "42", desc:"Fade"},{value: "16", desc:"Falcon"}, 
{value: "136", desc:"Fern"},{value: "82", desc:"Flaunt"},{value: "12", desc:"Giraffe"},{value: "88", desc:"Ground"}, 
{value: "170", desc:"Harlequin"},{value: "1", desc:"Iridescent"},{value: "19", desc:"Jaguar"},{value: "14", desc:"Jupiter"}, 
{value: "26", desc:"Laced"},{value: "40", desc:"Leopard"},{value: "25", desc:"Lionfish"},{value: "411", desc:"Love"}, 
{value: "17", desc:"Metallic"},{value: "58", desc:"Mosaic"},{value: "283", desc:"Orb"},{value: "13", desc:"Petals"},{value: "318", desc:"Petrified"}, 
{value: "87", desc:"Pharaoh"},{value: "9", desc:"Piebald"},{value: "22", desc:"Pinstripe"},{value: "11", desc:"Poison"}, 
{value: "23", desc:"Python"},{value: "505", desc:"Ragged"},{value: "84", desc:"Ribbon"},{value: "5", desc:"Ripple"}, 
{value: "492", desc:"Sailfish"},{value: "18", desc:"Savanna"},{value: "15", desc:"Skink"},{value: "41", desc:"Slime"}, 
{value: "400", desc:"Soil"},{value: "4", desc:"Speckle"},{value: "517", desc:"Sphinxmoth"},{value: "24", desc:"Starmap"},{value: "59", desc:"Stitched"}, 
{value: "57", desc:"Swirl"},{value: "21", desc:"Tapir"},{value: "114", desc:"Tide"},{value: "2", desc:"Tiger"},{value: "450", desc:"Varnish"}, 
{value: "8", desc:"Vipera"},{value: "20", desc:"Wasp"}],

"Gaoler": [{value: "34", desc:"Bar (Gaoler)"},{value: "171", desc:"Boa (Gaoler)"},{value: "289", desc:"Boulder (Gaoler)"},
{value: "391", desc:"Caterpillar (Gaoler)"},{value: "378", desc:"Checkers (Gaoler)"},{value: "216", desc:"Cinder (Gaoler)"},
{value: "77", desc:"Clown (Gaoler)"},{value: "37", desc:"Crystal (Gaoler)"},{value: "86", desc:"Fade (Gaoler)"},{value: "30", desc:"Falcon (Gaoler)"},
{value: "111", desc:"Flaunt (Gaoler)"},{value: "27", desc:"Giraffe (Gaoler)"},{value: "379", desc:"Harlequin (Gaoler)"},{value: "33", desc:"Jaguar (Gaoler)"},{value: "73", desc:"Laced (Gaoler)"},
{value: "173", desc:"Leopard (Gaoler)"},{value: "380", desc:"Lionfish (Gaoler)"},{value: "38", desc:"Mosaic (Gaoler)"},{value: "286", desc:"Orb (Gaoler)"},
{value: "39", desc:"Phantom (Gaoler)"},{value: "31", desc:"Piebald (Gaoler)"},{value: "32", desc:"Pinstripe (Gaoler)"},{value: "174", desc:"Poison (Gaoler)"},{value: "175", desc:"Ribbon (Gaoler)"},
{value: "78", desc:"Ripple (Gaoler)"},{value: "498", desc:"Sailfish (Gaoler)"},{value: "176", desc:"Savanna (Gaoler)"},{value: "29", desc:"Shaggy (Gaoler)"},{value: "177", desc:"Skink (Gaoler)"},
{value: "178", desc:"Slime (Gaoler)"},{value: "406", desc:"Soil (Gaoler)"},{value: "523", desc:"Sphinxmoth (Gaoler)"},
{value: "180", desc:"Stitched (Gaoler)"},{value: "179", desc:"Swirl (Gaoler)"},{value: "35", desc:"Tapir (Gaoler)"},{value: "172", desc:"Tide (Gaoler)"},
{value: "36", desc:"Tiger (Gaoler)"},{value: "381", desc:"Varnish (Gaoler)"},{value: "396", desc:"Vipera (Gaoler)"},{value: "28", desc:"Wasp (Gaoler)"}],

"Banescale": [{value: "181", desc:"Bar (Banescale)"},
{value: "235", desc:"Boa (Banescale)"},{value: "291", desc:"Boulder (Banescale)"},{value: "55", desc:"Candycane (Banescale)"},
{value: "388", desc:"Caterpillar (Banescale)"},{value: "454", desc:"Checkers (Banescale)"},{value: "43", desc:"Cherub (Banescale)"},
{value: "54", desc:"Chevron (Banescale)"},{value: "215", desc:"Cinder (Banescale)"},{value: "75", desc:"Clown (Banescale)"},{value: "182", desc:"Crystal (Banescale)"},
{value: "85", desc:"Fade (Banescale)"},{value: "80", desc:"Falcon (Banescale)"},{value: "137", desc:"Fern (Banescale)"},{value: "81", desc:"Giraffe (Banescale)"},
{value: "44", desc:"Jaguar (Banescale)"},{value: "48", desc:"Laced (Banescale)"},{value: "109", desc:"Leopard (Banescale)"},{value: "47", desc:"Marble (Banescale)"},
{value: "49", desc:"Metallic (Banescale)"},{value: "342", desc:"Mosaic (Banescale)"},{value: "287", desc:"Orb (Banescale)"},
{value: "51", desc:"Petals (Banescale)"},{value: "185", desc:"Pharaoh (Banescale)"},{value: "45", desc:"Pinstripe (Banescale)"},{value: "53", desc:"Poison (Banescale)"},
{value: "56", desc:"Ragged (Banescale)"},{value: "183", desc:"Ribbon (Banescale)"},{value: "79", desc:"Ripple (Banescale)"},{value: "50", desc:"Savanna (Banescale)"},
{value: "52", desc:"Skink (Banescale)"},{value: "404", desc:"Soil (Banescale)"},{value: "147", desc:"Speckle (Banescale)"},{value: "521", desc:"Sphinxmoth (Banescale)"},
{value: "74", desc:"Tapir (Banescale)"},{value: "184", desc:"Tide (Banescale)"},{value: "46", desc:"Tiger (Banescale)"},{value: "452", desc:"Varnish (Banescale)"},
{value: "395", desc:"Vipera (Banescale)"}], 

"Veilspun": [{value: "70", desc:"Arc (Veilspun)"},{value: "145", desc:"Bar (Veilspun)"},{value: "236", desc:"Boa (Veilspun)"},
{value: "290", desc:"Boulder (Veilspun)"},{value: "69", desc:"Bright (Veilspun)"},{value: "385", desc:"Caterpillar (Veilspun)"},
{value: "456", desc:"Checkers (Veilspun)"},{value: "339", desc:"Cherub (Veilspun)"},{value: "338", desc:"Chorus (Veilspun)"},
{value: "219", desc:"Cinder (Veilspun)"},{value: "76", desc:"Clown (Veilspun)"},{value: "146", desc:"Crystal (Veilspun)"},
{value: "60", desc:"Fade (Veilspun)"},{value: "139", desc:"Falcon (Veilspun)"},{value: "138", desc:"Fern (Veilspun)"},
{value: "83", desc:"Giraffe (Veilspun)"},{value: "382", desc:"Ground (Veilspun)"},{value: "376", desc:"Jaguar (Veilspun)"},
{value: "64", desc:"Jupiter (Veilspun)"},{value: "61", desc:"Laced (Veilspun)"},{value: "142", desc:"Leopard (Veilspun)"},
{value: "344", desc:"Mosaic (Veilspun)"},{value: "285", desc:"Orb (Veilspun)"},{value: "143", desc:"Petals (Veilspun)"},
{value: "383", desc:"Pharaoh (Veilspun)"},{value: "140", desc:"Poison (Veilspun)"},{value: "508", desc:"Ragged (Veilspun)"},{value: "500", desc:"Sailfish (Veilspun)"},
{value: "71", desc:"Shell (Veilspun)"},{value: "67", desc:"Skink (Veilspun)"},{value: "141", desc:"Slime (Veilspun)"},{value: "409", desc:"Soil (Veilspun)"},
{value: "144", desc:"Speckle (Veilspun)"},{value: "72", desc:"Sphinxmoth (Veilspun)"},{value: "65", desc:"Starmap (Veilspun)"},{value: "66", desc:"Stitched (Veilspun)"},
{value: "62", desc:"Tapir (Veilspun)"},{value: "453", desc:"Varnish (Veilspun)"},{value: "63", desc:"Vipera (Veilspun)"},
{value: "68", desc:"Wasp (Veilspun)"},{value: "384", desc:"Wrought (Veilspun)"}],

"Aberration": [{value: "89", desc:"Bar (Aberration)"},{value: "233", desc:"Boa (Aberration)"},{value: "220", desc:"Boulder (Aberration)"},
{value: "386", desc:"Caterpillar (Aberration)"},{value: "413", desc:"Checkers (Aberration)"},{value: "221", desc:"Cherub (Aberration)"},
{value: "214", desc:"Cinder (Aberration)"},{value: "222", desc:"Clown (Aberration)"},{value: "91", desc:"Crystal (Aberration)"},
{value: "93", desc:"Diamond (Aberration)"},{value: "90", desc:"Fade (Aberration)"},{value: "92", desc:"Falcon (Aberration)"},
{value: "223", desc:"Fern (Aberration)"},{value: "112", desc:"Flaunt (Aberration)"},{value: "94", desc:"Giraffe (Aberration)"},
{value: "97", desc:"Ground (Aberration)"},{value: "224", desc:"Harlequin (Aberration)"},{value: "99", desc:"Jaguar (Aberration)"},
{value: "225", desc:"Leopard (Aberration)"},{value: "100", desc:"Lionfish (Aberration)"},{value: "341", desc:"Mosaic (Aberration)"},
{value: "102", desc:"Orb (Aberration)"},{value: "101", desc:"Pharaoh (Aberration)"},{value: "226", desc:"Pinstripe (Aberration)"},
{value: "227", desc:"Poison (Aberration)"},{value: "105", desc:"Ribbon (Aberration)"},{value: "228", desc:"Ripple (Aberration)"},
{value: "493", desc:"Sailfish (Aberration)"},{value: "103", desc:"Savanna (Aberration)"},{value: "229", desc:"Skink (Aberration)"},
{value: "106", desc:"Slime (Aberration)"},{value: "401", desc:"Soil (Aberration)"},{value: "98", desc:"Speckle (Aberration)"},
{value: "518", desc:"Sphinxmoth (Aberration)"},{value: "230", desc:"Starmap (Aberration)"},{value: "107", desc:"Stitched (Aberration)"},
{value: "104", desc:"Swirl (Aberration)"},{value: "95", desc:"Tapir (Aberration)"},{value: "231", desc:"Tide (Aberration)"},
{value: "451", desc:"Varnish (Aberration)"},{value: "96", desc:"Vipera (Aberration)"},{value: "108", desc:"Wasp (Aberration)"}],

"Undertide": [{value: "117", desc:"Bar (Undertide)"},{value: "128", desc:"Boa (Undertide)"},{value: "135", desc:"Boulder (Undertide)"},{value: "390", desc:"Caterpillar (Undertide)"},
{value: "127", desc:"Checkers (Undertide)"},{value: "119", desc:"Cherub (Undertide)"},{value: "264", desc:"Chrysocolla (Undertide)"},
{value: "218", desc:"Cinder (Undertide)"},{value: "265", desc:"Clown (Undertide)"},{value: "118", desc:"Crystal (Undertide)"},
{value: "115", desc:"Fade (Undertide)"},{value: "122", desc:"Falcon (Undertide)"},{value: "266", desc:"Fern (Undertide)"},
{value: "267", desc:"Flaunt (Undertide)"},{value: "123", desc:"Giraffe (Undertide)"},{value: "268", desc:"Ground (Undertide)"},
{value: "280", desc:"Harlequin (Undertide)"},{value: "269", desc:"Jaguar (Undertide)"},{value: "270", desc:"Jupiter (Undertide)"},
{value: "126", desc:"Lionfish (Undertide)"},{value: "278", desc:"Metallic (Undertide)"},{value: "133", desc:"Octopus (Undertide)"},
{value: "271", desc:"Orb (Undertide)"},{value: "281", desc:"Petals (Undertide)"},{value: "120", desc:"Pharaoh (Undertide)"},
{value: "272", desc:"Piebald (Undertide)"},{value: "121", desc:"Pinstripe (Undertide)"},{value: "131", desc:"Poison (Undertide)"},{value: "124", desc:"Ribbon (Undertide)"},
{value: "130", desc:"Ripple (Undertide)"},{value: "499", desc:"Sailfish (Undertide)"},{value: "129", desc:"Savanna (Undertide)"},{value: "408", desc:"Soil (Undertide)"},
{value: "132", desc:"Speckle (Undertide)"},{value: "524", desc:"Sphinxmoth (Undertide)"},{value: "273", desc:"Starmap (Undertide)"},
{value: "282", desc:"Stitched (Undertide)"},{value: "134", desc:"Swirl (Undertide)"},{value: "274", desc:"Tapir (Undertide)"},
{value: "113", desc:"Tide (Undertide)"},{value: "275", desc:"Tiger (Undertide)"},{value: "276", desc:"Varnish (Undertide)"},
{value: "398", desc:"Vipera (Undertide)"},{value: "125", desc:"Wasp (Undertide)"},{value: "116", desc:"Wolf (Undertide)"},{value: "277", desc:"Wrought (Undertide)"}] ,

"Aether": [{value: "150", desc:"Bar (Aether)"},{value: "234", desc:"Boa (Aether)"},{value: "151", desc:"Boulder (Aether)"},
{value: "167", desc:"Candy (Aether)"},{value: "387", desc:"Caterpillar (Aether)"},{value: "319", desc:"Checkers (Aether)"},
{value: "320", desc:"Chrysocolla (Aether)"},{value: "163", desc:"Cinder (Aether)"},{value: "169", desc:"Clown (Aether)"},
{value: "321", desc:"Crystal (Aether)"},{value: "148", desc:"Fade (Aether)"},{value: "322", desc:"Falcon (Aether)"},
{value: "323", desc:"Fern (Aether)"},{value: "149", desc:"Flaunt (Aether)"},{value: "324", desc:"Giraffe (Aether)"},
{value: "325", desc:"Ground (Aether)"},{value: "326", desc:"Harlequin (Aether)"},{value: "152", desc:"Jaguar (Aether)"},
{value: "153", desc:"Jupiter (Aether)"},{value: "156", desc:"Laced (Aether)"},{value: "158", desc:"Lionfish (Aether)"},
{value: "157", desc:"Metallic (Aether)"},{value: "155", desc:"Mosaic (Aether)"},{value: "288", desc:"Orb (Aether)"},
{value: "154", desc:"Petals (Aether)"},{value: "159", desc:"Piebald (Aether)"},{value: "160", desc:"Python (Aether)"},
{value: "327", desc:"Ribbon (Aether)"},{value: "328", desc:"Ripple (Aether)"},{value: "494", desc:"Sailfish (Aether)"},
{value: "329", desc:"Savanna (Aether)"},{value: "161", desc:"Skink (Aether)"},{value: "336", desc:"Slime (Aether)"},
{value: "402", desc:"Soil (Aether)"},{value: "519", desc:"Sphinxmoth (Aether)"},{value: "162", desc:"Spool (Aether)"},
{value: "168", desc:"Starmap (Aether)"},{value: "165", desc:"Stitched (Aether)"},{value: "330", desc:"Tapir (Aether)"},
{value: "164", desc:"Tide (Aether)"},{value: "331", desc:"Tiger (Aether)"},{value: "166", desc:"Twinkle (Aether)"},
{value: "332", desc:"Varnish (Aether)"},{value: "333", desc:"Vipera (Aether)"},{value: "334", desc:"Wasp (Aether)"},{value: "335", desc:"Wrought (Aether)"}],

"Sandsurge": [{value: "194", desc:"Arapaima (Sandsurge)"},{value: "444", desc:"Bar (Sandsurge)"},{value: "189", desc:"Boa (Sandsurge)"},
{value: "188", desc:"Boulder (Sandsurge)"},{value: "392", desc:"Caterpillar (Sandsurge)"},{value: "440", desc:"Checkers (Sandsurge)"},
{value: "190", desc:"Cherub (Sandsurge)"},{value: "195", desc:"Chrysocolla (Sandsurge)"},{value: "217", desc:"Cinder (Sandsurge)"},
{value: "196", desc:"Clown (Sandsurge)"},{value: "399", desc:"Crystal (Sandsurge)"},{value: "191", desc:"Fade (Sandsurge)"},
{value: "448", desc:"Falcon (Sandsurge)"},{value: "394", desc:"Fern (Sandsurge)"},{value: "193", desc:"Flaunt (Sandsurge)"},
{value: "186", desc:"Ground (Sandsurge)"},{value: "192", desc:"Harlequin (Sandsurge)"},{value: "198", desc:"Jaguar (Sandsurge)"},{value: "197", desc:"Jupiter (Sandsurge)"},
{value: "199", desc:"Lionfish (Sandsurge)"},{value: "200", desc:"Mosaic (Sandsurge)"},{value: "284", desc:"Orb (Sandsurge)"},
{value: "446", desc:"Petals (Sandsurge)"},{value: "449", desc:"Petrified (Sandsurge)"},{value: "201", desc:"Piebald (Sandsurge)"},
{value: "202", desc:"Pinstripe (Sandsurge)"},{value: "203", desc:"Python (Sandsurge)"},{value: "445", desc:"Ragged (Sandsurge)"},
{value: "206", desc:"Rattlesnake (Sandsurge)"},{value: "447", desc:"Ribbon (Sandsurge)"},{value: "212", desc:"Sailfish (Sandsurge)"},
{value: "204", desc:"Savanna (Sandsurge)"},{value: "441", desc:"Skink (Sandsurge)"},{value: "208", desc:"Slime (Sandsurge)"},
{value: "407", desc:"Soil (Sandsurge)"},{value: "443", desc:"Sphinxmoth (Sandsurge)"},{value: "209", desc:"Swirl (Sandsurge)"},
{value: "210", desc:"Tapir (Sandsurge)"},{value: "211", desc:"Tiger (Sandsurge)"},{value: "442", desc:"Varnish (Sandsurge)"},
{value: "397", desc:"Vipera (Sandsurge)"},{value: "207", desc:"Wasp (Sandsurge)"},{value: "187", desc:"Wrought (Sandsurge)"}],

"Auraboa": [{value: "238", desc:"Bar (Auraboa)"},{value: "239", desc:"Boa (Auraboa)"},{value: "240", desc:"Boulder (Auraboa)"},
{value: "241", desc:"Caterpillar (Auraboa)"},{value: "455", desc:"Checkers (Auraboa)"},{value: "504", desc:"Cherub (Auraboa)"},
{value: "242", desc:"Fade (Auraboa)"},{value: "243", desc:"Falcon (Auraboa)"},{value: "244", desc:"Fern (Auraboa)"},{value: "245", desc:"Flaunt (Auraboa)"},
{value: "246", desc:"Giraffe (Auraboa)"},{value: "247", desc:"Harlequin (Auraboa)"},{value: "248", desc:"Jaguar (Auraboa)"},{value: "249", desc:"Laced (Auraboa)"},
{value: "279", desc:"Love (Auraboa)"},{value: "250", desc:"Metallic (Auraboa)"},{value: "251", desc:"Mochlus (Auraboa)"},
{value: "252", desc:"Mosaic (Auraboa)"},{value: "253", desc:"Orb (Auraboa)"},{value: "502", desc:"Petrified (Auraboa)"},{value: "254", desc:"Piebald (Auraboa)"},
{value: "255", desc:"Python (Auraboa)"},{value: "506", desc:"Ragged (Auraboa)"},{value: "256", desc:"Rattlesnake (Auraboa)"},
{value: "257", desc:"Ripple (Auraboa)"},{value: "495", desc:"Sailfish (Auraboa)"},{value: "503", desc:"Slime (Auraboa)"},
{value: "403", desc:"Soil (Auraboa)"},{value: "520", desc:"Sphinxmoth (Auraboa)"},{value: "501", desc:"Spool (Auraboa)"},{value: "263", desc:"Starmap (Auraboa)"},
{value: "258", desc:"Tapir (Auraboa)"},{value: "259", desc:"Tiger (Auraboa)"},{value: "261", desc:"Varnish (Auraboa)"},
{value: "260", desc:"Vipera (Auraboa)"},{value: "262", desc:"Wicker (Auraboa)"}],

"Dusthide": [{value: "545", desc:"Arapaima (Dusthide)"},{value: "306", desc:"Arc (Dusthide)"},{value: "292", desc:"Bar (Dusthide)"},
{value: "389", desc:"Caterpillar (Dusthide)"},{value: "293", desc:"Checkers (Dusthide)"},{value: "340", desc:"Cherub (Dusthide)"},
{value: "549", desc:"Chorus (Dusthide)"},{value: "546", desc:"Chrysocolla (Dusthide)"},{value: "295", desc:"Cinder (Dusthide)"},
{value: "551", desc:"Criculaworm (Dusthide)"},{value: "547", desc:"Crystal (Dusthide)"},{value: "317", desc:"Display (Dusthide)"},
{value: "296", desc:"Fade (Dusthide)"},{value: "301", desc:"Falcon (Dusthide)"},{value: "548", desc:"Fern (Dusthide)"},
{value: "297", desc:"Giraffe (Dusthide)"},{value: "299", desc:"G+round (Dusthide)"},{value: "298", desc:"Harlequin (Dusthide)"},
{value: "550", desc:"Jaguar (Dusthide)"},{value: "300", desc:"Jupiter (Dusthide)"},{value: "302", desc:"Laced (Dusthide)"},
{value: "552", desc:"Marble (Dusthide)"},{value: "553", desc:"Metallic (Dusthide)"},{value: "343", desc:"Mosaic (Dusthide)"},
{value: "303", desc:"Orb (Dusthide)"},{value: "304", desc:"Petals (Dusthide)"},{value: "309", desc:"Petrified (Dusthide)"},
{value: "554", desc:"Pharaoh (Dusthide)"},{value: "305", desc:"Piebald (Dusthide)"},{value: "308", desc:"Pinstripe (Dusthide)"},
{value: "555", desc:"Poison (Dusthide)"},{value: "556", desc:"Python (Dusthide)"},{value: "507", desc:"Ragged (Dusthide)"},
{value: "557", desc:"Rattlesnake (Dusthide)"},{value: "311", desc:"Ribbon (Dusthide)"},
{value: "312", desc:"Ripple (Dusthide)"},{value: "313", desc:"Sailfish (Dusthide)"},{value: "314", desc:"Savanna (Dusthide)"},
{value: "315", desc:"Skink (Dusthide)"},{value: "558", desc:"Slime (Dusthide)"},{value: "405", desc:"Soil (Dusthide)"},
{value: "294", desc:"Speckle (Dusthide)"},{value: "522", desc:"Sphinxmoth (Dusthide)"},{value: "205", desc:"Strike (Dusthide)"},
{value: "559", desc:"Swirl (Dusthide)"},{value: "560", desc:"Tapir (Dusthide)"},{value: "561", desc:"Tide (Dusthide)"},
{value: "316", desc:"Varnish (Dusthide)"},{value: "562", desc:"Vipera (Dusthide)"},{value: "310", desc:"Wasp (Dusthide)"},
{value: "307", desc:"Wrought (Dusthide)"}],

"Everlux": [{value: "345", desc:"Arapaima (Everlux)"},{value: "346", desc:"Bar (Everlux)"},{value: "347", desc:"Caterpillar (Everlux)"},
{value: "348", desc:"Cherub (Everlux)"},{value: "349", desc:"Chorus (Everlux)"},{value: "350", desc:"Chrysocolla (Everlux)"},
{value: "351", desc:"Criculaworm (Everlux)"},{value: "352", desc:"Crystal (Everlux)"},{value: "353", desc:"Fade (Everlux)"},
{value: "354", desc:"Flaunt (Everlux)"},{value: "510", desc:"Jaguar (Everlux)"},{value: "355", desc:"Jupiter (Everlux)"},
{value: "356", desc:"Laced (Everlux)"},{value: "357", desc:"Lionfish (Everlux)"},{value: "358", desc:"Marble (Everlux)"},
{value: "359", desc:"Papillon (Everlux)"},{value: "360", desc:"Petals (Everlux)"},{value: "361", desc:"Petrified (Everlux)"},
{value: "362", desc:"Pharaoh (Everlux)"},{value: "363", desc:"Piebald (Everlux)"},{value: "365", desc:"Pinstripe (Everlux)"},
{value: "370", desc:"Poison (Everlux)"},{value: "364", desc:"Python (Everlux)"},{value: "509", desc:"Ragged (Everlux)"},
{value: "366", desc:"Ripple (Everlux)"},{value: "497", desc:"Sailfish (Everlux)"},{value: "367", desc:"Skink (Everlux)"},
{value: "368", desc:"Slime (Everlux)"},{value: "410", desc:"Soil (Everlux)"},{value: "369", desc:"Sphinxmoth (Everlux)"},
{value: "371", desc:"Starmap (Everlux)"},{value: "372", desc:"Strike (Everlux)"},{value: "377", desc:"Throne (Everlux)"},
{value: "373", desc:"Tide (Everlux)"},{value: "374", desc:"Tiger (Everlux)"},{value: "375", desc:"Varnish (Everlux)"}],

"Cirrus": [{value: "416", desc:"Arc (Cirrus)"},{value: "417", desc:"Bar (Cirrus)"},{value: "419", desc:"Cherub (Cirrus)"},
{value: "420", desc:"Chorus (Cirrus)"},{value: "421", desc:"Cinder (Cirrus)"},{value: "414", desc:"Criculaworm (Cirrus)"},
{value: "422", desc:"Fade (Cirrus)"},{value: "418", desc:"Faire (Cirrus)"},{value: "423", desc:"Flaunt (Cirrus)"},
{value: "427", desc:"Harlequin (Cirrus)"},{value: "426", desc:"Ink (Cirrus)"},{value: "424", desc:"Marble (Cirrus)"},{value: "429", desc:"Metallic (Cirrus)"},
{value: "425", desc:"Orb (Cirrus)"},{value: "428", desc:"Piebald (Cirrus)"},{value: "430", desc:"Python (Cirrus)"},
{value: "439", desc:"Rabicano (Cirrus)"},{value: "431", desc:"Ragged (Cirrus)"},{value: "432", desc:"Ripple (Cirrus)"},
{value: "496", desc:"Sailfish (Cirrus)"},{value: "415", desc:"Savanna (Cirrus)"},{value: "437", desc:"Skink (Cirrus)"},
{value: "438", desc:"Soil (Cirrus)"},{value: "436", desc:"Tiger (Cirrus)"},{value: "435", desc:"Varnish (Cirrus)"},{value: "434", desc:"Vipera (Cirrus)"},
{value: "433", desc:"Wasp (Cirrus)"}],

"Vigil": [{value: "511", desc:"Arapaima (Vigil)"},{value: "512", desc:"Bar (Vigil)"},{value: "514", desc:"Caterpillar (Vigil)"},
{value: "515", desc:"Checkers (Vigil)"},{value: "525", desc:"Cinder (Vigil)"},{value: "513", desc:"Clown (Vigil)"},{value: "526", desc:"Criculaworm (Vigil)"},
{value: "527", desc:"Crosshatch (Vigil)"},{value: "528", desc:"Dimension (Vigil)"},{value: "529", desc:"Fade (Vigil)"},{value: "530", desc:"Jaguar (Vigil)"},
{value: "531", desc:"Leopard (Vigil)"},{value: "532", desc:"Marble (Vigil)"},{value: "533", desc:"Metallic (Vigil)"},{value: "534", desc:"Patina (Vigil)"},
{value: "535", desc:"Piebald (Vigil)"},{value: "536", desc:"Ribbon (Vigil)"},{value: "537", desc:"Ripple (Vigil)"},{value: "538", desc:"Sailfish (Vigil)"},
{value: "539", desc:"Skink (Vigil)"},{value: "516", desc:"Strike (Vigil)"},{value: "540", desc:"Swirl (Vigil)"},{value: "541", desc:"Tapir (Vigil)"},
{value: "544", desc:"Varnish (Vigil)"},{value: "542", desc:"Vipera (Vigil)"},{value: "543", desc:"Wrought (Vigil)"}],

"Thorntail": [{value: "458", desc:"Arapaima (Thorntail)"},{value: "457", desc:"Arc (Thorntail)"},{value: "460", desc:"Bar (Thorntail)"},
{value: "462", desc:"Boa (Thorntail)"},{value: "463", desc:"Caiman (Thorntail)"},{value: "464", desc:"Candycane (Thorntail)"},
{value: "465", desc:"Cherub (Thorntail)"},{value: "466", desc:"Chorus (Thorntail)"},{value: "467", desc:"Cinder (Thorntail)"},
{value: "468", desc:"Criculaworm (Thorntail)"},{value: "459", desc:"Dimension (Thorntail)"},{value: "469", desc:"Fade (Thorntail)"},
{value: "470", desc:"Fern (Thorntail)"},{value: "489", desc:"Glass (Thorntail)"},{value: "461", desc:"Glow (Thorntail)"},{value: "471", desc:"Ink (Thorntail)"},
{value: "472", desc:"Jaguar (Thorntail)"},{value: "473", desc:"Marble (Thorntail)"},{value: "474", desc:"Orb (Thorntail)"},{value: "475", desc:"Petals (Thorntail)"},
{value: "476", desc:"Pharaoh (Thorntail)"},{value: "477", desc:"Piebald (Thorntail)"},{value: "478", desc:"Python (Thorntail)"},
{value: "490", desc:"Radio (Thorntail)"},{value: "479", desc:"Ragged (Thorntail)"},{value: "480", desc:"Rattlesnake (Thorntail)"},
{value: "481", desc:"Ripple (Thorntail)"},{value: "482", desc:"Sailfish (Thorntail)"},{value: "483", desc:"Skink (Thorntail)"},
{value: "484", desc:"Soil (Thorntail)"},{value: "491", desc:"Splatter (Thorntail)"},{value: "485", desc:"Tapir (Thorntail)"},{value: "486", desc:"Tide (Thorntail)"},
{value: "487", desc:"Varnish (Thorntail)"},{value: "488", desc:"Vipera (Thorntail)"}]};

//secondary genes - sorted by modern and each ancient breed for easier insertions
const secondaryGenes ={"Modern": [{value: "411", desc:"Affection"},{value: "17", desc:"Alloy"},{value: "0", desc:"Basic"},{value: "20", desc:"Bee"},{value: "213", desc:"Blaze"},{value: "42", desc:"Blend"},
{value: "58", desc:"Breakup"},{value: "13", desc:"Butterfly"},{value: "412", desc:"Chess"},{value: "337", desc:"Choir"},{value: "40", desc:"Clouded"},
{value: "25", desc:"Constellation"},{value: "6", desc:"Current"},{value: "7", desc:"Daub"},{value: "26", desc:"Edged"},{value: "84", desc:"Eel"},
{value: "3", desc:"Eye Spots"},{value: "8", desc:"Facet"},{value: "88", desc:"Fissure"},{value: "82", desc:"Flair"},{value: "113", desc:"Foam"},
{value: "4", desc:"Freckle"},{value: "517", desc:"Hawkmoth"},{value: "14", desc:"Hex"},{value: "9", desc:"Hypnotic"},{value: "170", desc:"Jester"},
{value: "450", desc:"Lacquer"},{value: "400", desc:"Loam"},{value: "318", desc:"Lode"},{value: "237", desc:"Malachite"},{value: "57", desc:"Marbled"},
{value: "492", desc:"Marlin"},{value: "23", desc:"Morph"},{value: "110", desc:"Myrid"},{value: "24", desc:"Noxtide"},{value: "10", desc:"Paint"},
{value: "136", desc:"Paisley"},{value: "59", desc:"Patchwork"},{value: "11", desc:"Peregrine"},{value: "19", desc:"Rosette"},{value: "232", desc:"Saddle"},
{value: "18", desc:"Safari"},{value: "87", desc:"Sarcophagus"},{value: "15", desc:"Saturn"},{value: "5", desc:"Seraph"},{value: "1", desc:"Shimmer"},
{value: "41", desc:"Sludge"},{value: "16", desc:"Spinner"},{value: "21", desc:"Striation"},{value: "2", desc:"Stripes"},{value: "505", desc:"Tear"},
{value: "12", desc:"Toxin"},{value: "22", desc:"Trail"},{value: "283", desc:"Weaver"}],

"Gaoler": [{value: "28", desc:"Bee (Gaoler)"},{value: "216", desc:"Blaze (Gaoler)"},{value: "86", desc:"Blend (Gaoler)"},{value: "38", desc:"Breakup (Gaoler)"},
{value: "379", desc:"Chess (Gaoler)"},{value: "180", desc:"Clouded (Gaoler)"},{value: "78", desc:"Current (Gaoler)"},{value: "34", desc:"Daub (Gaoler)"},
{value: "73", desc:"Edged (Gaoler)"},{value: "174", desc:"Eel (Gaoler)"},{value: "77", desc:"Eye Spots (Gaoler)"},{value: "37", desc:"Facet (Gaoler)"},
{value: "111", desc:"Flair (Gaoler)"},{value: "172", desc:"Foam (Gaoler)"},{value: "523", desc:"Hawkmoth (Gaoler)"},{value: "27", desc:"Hex (Gaoler)"},
{value: "396", desc:"Hypnotic (Gaoler)"},{value: "380", desc:"Jester (Gaoler)"},{value: "382", desc:"Lacquer (Gaoler)"},{value: "392", desc:"Larvae (Gaoler)"},
{value: "406", desc:"Loam (Gaoler)"},{value: "178", desc:"Marbled (Gaoler)"},{value: "498", desc:"Marlin (Gaoler)"},{value: "290", desc:"Myrid (Gaoler)"},
{value: "381", desc:"Noxtide (Gaoler)"},{value: "31", desc:"Paint (Gaoler)"},{value: "179", desc:"Patchwork (Gaoler)"},{value: "30", desc:"Peregrine (Gaoler)"},
{value: "33", desc:"Rosette (Gaoler)"},{value: "171", desc:"Saddle (Gaoler)"},{value: "175", desc:"Safari (Gaoler)"},{value: "177", desc:"Sludge (Gaoler)"},
{value: "176", desc:"Spinner (Gaoler)"},{value: "39", desc:"Spirit (Gaoler)"},{value: "29", desc:"Streak (Gaoler)"},{value: "35", desc:"Striation (Gaoler)"},
{value: "36", desc:"Stripes (Gaoler)"},{value: "173", desc:"Toxin (Gaoler)"},{value: "32", desc:"Trail (Gaoler)"},{value: "286", desc:"Weaver (Gaoler)"}],

"Banesclae": [{value: "49", desc:"Alloy (Banescale)"},{value: "54", desc:"Arrow (Banescale)"},{value: "215", desc:"Blaze (Banescale)"},{value: "85", desc:"Blend (Banescale)"},
{value: "342", desc:"Breakup (Banescale)"},{value: "51", desc:"Butterfly (Banescale)"},{value: "455", desc:"Chess (Banescale)"},{value: "109", desc:"Clouded (Banescale)"},
{value: "79", desc:"Current (Banescale)"},{value: "181", desc:"Daub (Banescale)"},{value: "48", desc:"Edged (Banescale)"},{value: "183", desc:"Eel (Banescale)"},
{value: "75", desc:"Eye Spots (Banescale)"},{value: "182", desc:"Facet (Banescale)"},{value: "184", desc:"Foam (Banescale)"},{value: "147", desc:"Freckle (Banescale)"},
{value: "521", desc:"Hawkmoth (Banescale)"},{value: "81", desc:"Hex (Banescale)"},{value: "395", desc:"Hypnotic (Banescale)"},{value: "452", desc:"Lacquer (Banescale)"},
{value: "388", desc:"Larvae (Banescale)"},{value: "404", desc:"Loam (Banescale)"},{value: "47", desc:"Mottle (Banescale)"},{value: "289", desc:"Myrid (Banescale)"},
{value: "137", desc:"Paisley (Banescale)"},{value: "80", desc:"Peregrine (Banescale)"},{value: "44", desc:"Rosette (Banescale)"},{value: "235", desc:"Saddle (Banescale)"},
{value: "50", desc:"Safari (Banescale)"},{value: "185", desc:"Sarcophagus (Banescale)"},{value: "43", desc:"Seraph (Banescale)"},{value: "52", desc:"Spinner (Banescale)"},
{value: "74", desc:"Striation (Banescale)"},{value: "46", desc:"Stripes (Banescale)"},{value: "55", desc:"Sugarplum (Banescale)"},{value: "56", desc:"Tear (Banescale)"},
{value: "53", desc:"Toxin (Banescale)"},{value: "45", desc:"Trail (Banescale)"},{value: "285", desc:"Weaver (Banescale)"}],

"Veilspun": [{value: "60", desc:"Bee (Veilspun)"},{value: "219", desc:"Blaze (Veilspun)"},{value: "61", desc:"Blend (Veilspun)"},{value: "344", desc:"Breakup (Veilspun)"},
{value: "144", desc:"Butterfly (Veilspun)"},{value: "456", desc:"Chess (Veilspun)"},{value: "338", desc:"Choir (Veilspun)"},{value: "142", desc:"Clouded (Veilspun)"},
{value: "66", desc:"Constellation (Veilspun)"},{value: "145", desc:"Daub (Veilspun)"},{value: "62", desc:"Edged (Veilspun)"},{value: "76", desc:"Eye Spots (Veilspun)"},
{value: "146", desc:"Facet (Veilspun)"},{value: "377", desc:"Fissure (Veilspun)"},{value: "143", desc:"Freckle (Veilspun)"},{value: "72", desc:"Hawkmoth (Veilspun)"},
{value: "83", desc:"Hex (Veilspun)"},{value: "64", desc:"Hypnotic (Veilspun)"},{value: "453", desc:"Lacquer (Veilspun)"},{value: "385", desc:"Larvae (Veilspun)"},
{value: "409", desc:"Loam (Veilspun)"},{value: "70", desc:"Loop (Veilspun)"},{value: "500", desc:"Marlin (Veilspun)"},{value: "291", desc:"Myrid (Veilspun)"},
{value: "138", desc:"Paisley (Veilspun)"},{value: "67", desc:"Patchwork (Veilspun)"},{value: "139", desc:"Peregrine (Veilspun)"},{value: "383", desc:"Rosette (Veilspun)"},
{value: "236", desc:"Saddle (Veilspun)"},{value: "365", desc:"Sarcophagus (Veilspun)"},{value: "65", desc:"Saturn (Veilspun)"},{value: "339", desc:"Seraph (Veilspun)"},
{value: "141", desc:"Sludge (Veilspun)"},{value: "68", desc:"Spinner (Veilspun)"},{value: "384", desc:"Spire (Veilspun)"},{value: "63", desc:"Striation (Veilspun)"},
{value: "509", desc:"Tear (Veilspun)"},{value: "140", desc:"Toxin (Veilspun)"},{value: "69", desc:"Vivid (Veilspun)"},{value: "288", desc:"Weaver (Veilspun)"},
{value: "71", desc:"Web (Veilspun)"}],

"Aberration": [{value: "108", desc:"Bee (Aberration)"},{value: "214", desc:"Blaze (Aberration)"},{value: "91", desc:"Blend (Aberration)"},{value: "341", desc:"Breakup (Aberration)"},
{value: "413", desc:"Chess (Aberration)"},{value: "220", desc:"Clouded (Aberration)"},{value: "221", desc:"Constellation (Aberration)"},{value: "222", desc:"Current (Aberration)"},
{value: "89", desc:"Daub (Aberration)"},{value: "105", desc:"Eel (Aberration)"},{value: "223", desc:"Eye Spots (Aberration)"},{value: "90", desc:"Facet (Aberration)"},
{value: "97", desc:"Fissure (Aberration)"},{value: "112", desc:"Flair (Aberration)"},{value: "224", desc:"Foam (Aberration)"},{value: "98", desc:"Freckle (Aberration)"},
{value: "518", desc:"Hawkmoth (Aberration)"},{value: "94", desc:"Hex (Aberration)"},{value: "96", desc:"Hypnotic (Aberration)"},{value: "225", desc:"Jester (Aberration)"},
{value: "451", desc:"Lacquer (Aberration)"},{value: "386", desc:"Larvae (Aberration)"},{value: "401", desc:"Loam (Aberration)"},{value: "103", desc:"Marbled (Aberration)"},
{value: "493", desc:"Marlin (Aberration)"},{value: "226", desc:"Myrid (Aberration)"},{value: "100", desc:"Noxtide (Aberration)"},{value: "227", desc:"Paisley (Aberration)"},
{value: "107", desc:"Patchwork (Aberration)"},{value: "92", desc:"Peregrine (Aberration)"},{value: "99", desc:"Rosette (Aberration)"},{value: "233", desc:"Saddle (Aberration)"},
{value: "104", desc:"Safari (Aberration)"},{value: "101", desc:"Sarcophagus (Aberration)"},{value: "228", desc:"Seraph (Aberration)"},{value: "106", desc:"Sludge (Aberration)"},
{value: "93", desc:"Spade (Aberration)"},{value: "229", desc:"Spinner (Aberration)"},{value: "95", desc:"Striation (Aberration)"},{value: "230", desc:"Toxin (Aberration)"},
{value: "231", desc:"Trail (Aberration)"},{value: "102", desc:"Weaver (Aberration)"}],

"Undertide": [{value: "278", desc:"Alloy (Undertide)"},{value: "125", desc:"Bee (Undertide)"},{value: "218", desc:"Blaze (Undertide)"},{value: "115", desc:"Blend (Undertide)"},
{value: "281", desc:"Butterfly (Undertide)"},{value: "127", desc:"Chess (Undertide)"},{value: "273", desc:"Constellation (Undertide)"},{value: "130", desc:"Current (Undertide)"},
{value: "117", desc:"Daub (Undertide)"},{value: "124", desc:"Eel (Undertide)"},{value: "265", desc:"Eye Spots (Undertide)"},{value: "118", desc:"Facet (Undertide)"},
{value: "268", desc:"Fissure (Undertide)"},{value: "267", desc:"Flair (Undertide)"},{value: "114", desc:"Foam (Undertide)"},{value: "132", desc:"Freckle (Undertide)"},
{value: "524", desc:"Hawkmoth (Undertide)"},{value: "123", desc:"Hex (Undertide)"},{value: "398", desc:"Hypnotic (Undertide)"},{value: "282", desc:"Jester (Undertide)"},
{value: "276", desc:"Lacquer (Undertide)"},{value: "390", desc:"Larvae (Undertide)"},{value: "408", desc:"Loam (Undertide)"},{value: "264", desc:"Malachite (Undertide)"},
{value: "134", desc:"Marbled (Undertide)"},{value: "499", desc:"Marlin (Undertide)"},{value: "135", desc:"Myrid (Undertide)"},{value: "126", desc:"Noxtide (Undertide)"},
{value: "116", desc:"Pack (Undertide)"},{value: "272", desc:"Paint (Undertide)"},{value: "266", desc:"Paisley (Undertide)"},{value: "280", desc:"Patchwork (Undertide)"},
{value: "122", desc:"Peregrine (Undertide)"},{value: "133", desc:"Rings (Undertide)"},{value: "269", desc:"Rosette (Undertide)"},{value: "128", desc:"Saddle (Undertide)"},
{value: "129", desc:"Safari (Undertide)"},{value: "120", desc:"Sarcophagus (Undertide)"},{value: "270", desc:"Saturn (Undertide)"},{value: "119", desc:"Seraph (Undertide)"},
{value: "277", desc:"Spire (Undertide)"},{value: "274", desc:"Striation (Undertide)"},{value: "275", desc:"Stripes (Undertide)"},{value: "131", desc:"Toxin (Undertide)"},
{value: "121", desc:"Trail (Undertide)"},{value: "271", desc:"Weaver (Undertide)"}],

"Aether": [{value: "157", desc:"Alloy (Aether)"},{value: "319", desc:"Bee (Aether)"},{value: "163", desc:"Blaze (Aether)"},{value: "148", desc:"Blend (Aether)"},
{value: "155", desc:"Breakup (Aether)"},{value: "154", desc:"Butterfly (Aether)"},{value: "320", desc:"Chess (Aether)"},{value: "168", desc:"Constellation (Aether)"},
{value: "321", desc:"Current (Aether)"},{value: "150", desc:"Daub (Aether)"},{value: "156", desc:"Edged (Aether)"},{value: "322", desc:"Eel (Aether)"},
{value: "169", desc:"Eye Spots (Aether)"},{value: "323", desc:"Facet (Aether)"},{value: "324", desc:"Fissure (Aether)"},{value: "149", desc:"Flair (Aether)"},
{value: "166", desc:"Flicker (Aether)"},{value: "164", desc:"Foam (Aether)"},{value: "519", desc:"Hawkmoth (Aether)"},{value: "325", desc:"Hex (Aether)"},
{value: "326", desc:"Hypnotic (Aether)"},{value: "167", desc:"Icing (Aether)"},{value: "327", desc:"Jester (Aether)"},{value: "328", desc:"Lacquer (Aether)"},
{value: "387", desc:"Larvae (Aether)"},{value: "402", desc:"Loam (Aether)"},{value: "329", desc:"Malachite (Aether)"},{value: "494", desc:"Marlin (Aether)"},
{value: "160", desc:"Morph (Aether)"},{value: "151", desc:"Myrid (Aether)"},{value: "158", desc:"Noxtide (Aether)"},{value: "159", desc:"Paint (Aether)"},
{value: "330", desc:"Paisley (Aether)"},{value: "165", desc:"Patchwork (Aether)"},{value: "331", desc:"Peregrine (Aether)"},{value: "152", desc:"Rosette (Aether)"},
{value: "234", desc:"Saddle (Aether)"},{value: "332", desc:"Safari (Aether)"},{value: "153", desc:"Saturn (Aether)"},{value: "336", desc:"Sludge (Aether)"},
{value: "161", desc:"Spinner (Aether)"},{value: "335", desc:"Spire (Aether)"},{value: "333", desc:"Striation (Aether)"},{value: "334", desc:"Stripes (Aether)"},
{value: "162", desc:"Thread (Aether)"},{value: "284", desc:"Weaver (Aether)"}],

"Sandsurge": [{value: "194", desc:"Arowana (Sandsurge)"},{value: "207", desc:"Bee (Sandsurge)"},{value: "217", desc:"Blaze (Sandsurge)"},{value: "191", desc:"Blend (Sandsurge)"},
{value: "200", desc:"Breakup (Sandsurge)"},{value: "446", desc:"Butterfly (Sandsurge)"},{value: "440", desc:"Chess (Sandsurge)"},{value: "444", desc:"Daub (Sandsurge)"},
{value: "206", desc:"Diamondback (Sandsurge)"},{value: "447", desc:"Eel (Sandsurge)"},{value: "196", desc:"Eye Spots (Sandsurge)"},{value: "399", desc:"Facet (Sandsurge)"},
{value: "186", desc:"Fissure (Sandsurge)"},{value: "193", desc:"Flair (Sandsurge)"},{value: "443", desc:"Hawkmoth (Sandsurge)"},{value: "397", desc:"Hypnotic (Sandsurge)"},
{value: "192", desc:"Jester (Sandsurge)"},{value: "442", desc:"Lacquer (Sandsurge)"},{value: "391", desc:"Larvae (Sandsurge)"},{value: "407", desc:"Loam (Sandsurge)"},
{value: "449", desc:"Lode (Sandsurge)"},{value: "195", desc:"Malachite (Sandsurge)"},{value: "209", desc:"Marbled (Sandsurge)"},{value: "212", desc:"Marlin (Sandsurge)"},
{value: "203", desc:"Morph (Sandsurge)"},{value: "188", desc:"Myrid (Sandsurge)"},{value: "199", desc:"Noxtide (Sandsurge)"},{value: "201", desc:"Paint (Sandsurge)"},
{value: "394", desc:"Paisley (Sandsurge)"},{value: "448", desc:"Peregrine (Sandsurge)"},{value: "198", desc:"Rosette (Sandsurge)"},{value: "189", desc:"Saddle (Sandsurge)"},
{value: "204", desc:"Safari (Sandsurge)"},{value: "197", desc:"Saturn (Sandsurge)"},{value: "190", desc:"Seraph (Sandsurge)"},{value: "208", desc:"Sludge (Sandsurge)"},
{value: "441", desc:"Spinner (Sandsurge)"},{value: "187", desc:"Spire (Sandsurge)"},{value: "210", desc:"Striation (Sandsurge)"},{value: "211", desc:"Stripes (Sandsurge)"},
{value: "445", desc:"Tear (Sandsurge)"},{value: "202", desc:"Trail (Sandsurge)"},{value: "287", desc:"Weaver (Sandsurge)"}],

"Auraboa": [{value: "279", desc:"Affection (Auraboa)"},{value: "250", desc:"Alloy (Auraboa)"},{value: "242", desc:"Blend (Auraboa)"},{value: "252", desc:"Breakup (Auraboa)"},
{value: "454", desc:"Chess (Auraboa)"},{value: "263", desc:"Constellation (Auraboa)"},{value: "257", desc:"Current (Auraboa)"},{value: "238", desc:"Daub (Auraboa)"},
{value: "256", desc:"Diamondback (Auraboa)"},{value: "249", desc:"Edged (Auraboa)"},{value: "245", desc:"Flair (Auraboa)"},{value: "520", desc:"Hawkmoth (Auraboa)"},{value: "246", desc:"Hex (Auraboa)"},
{value: "260", desc:"Hypnotic (Auraboa)"},{value: "247", desc:"Jester (Auraboa)"},{value: "261", desc:"Lacquer (Auraboa)"},{value: "241", desc:"Larvae (Auraboa)"},
{value: "403", desc:"Loam (Auraboa)"},{value: "502", desc:"Lode (Auraboa)"},{value: "495", desc:"Marlin (Auraboa)"},{value: "255", desc:"Morph (Auraboa)"},
{value: "240", desc:"Myrid (Auraboa)"},{value: "254", desc:"Paint (Auraboa)"},{value: "244", desc:"Paisley (Auraboa)"},{value: "243", desc:"Peregrine (Auraboa)"},
{value: "251", desc:"Riopa (Auraboa)"},{value: "248", desc:"Rosette (Auraboa)"},{value: "239", desc:"Saddle (Auraboa)"},{value: "504", desc:"Seraph (Auraboa)"},
{value: "503", desc:"Sludge (Auraboa)"},{value: "258", desc:"Striation (Auraboa)"},{value: "259", desc:"Stripes (Auraboa)"},{value: "506", desc:"Tear (Auraboa)"},
{value: "501", desc:"Thread (Auraboa)"},{value: "253", desc:"Weaver (Auraboa)"},{value: "262", desc:"Woven (Auraboa)"}],

"Dusthide": [{value: "553", desc:"Alloy (Dusthide)"},{value: "545", desc:"Arowana (Dusthide)"},{value: "310", desc:"Bee (Dusthide)"},
{value: "295", desc:"Blaze (Dusthide)"},{value: "296", desc:"Blend (Dusthide)"},{value: "343", desc:"Breakup (Dusthide)"},{value: "304", desc:"Butterfly (Dusthide)"},
{value: "293", desc:"Chess (Dusthide)"},{value: "549", desc:"Choir (Dusthide)"},{value: "205", desc:"Coil (Dusthide)"},{value: "312", desc:"Current (Dusthide)"},{value: "292", desc:"Daub (Dusthide)"},
{value: "557", desc:"Diamondback (Dusthide)"},{value: "302", desc:"Edged (Dusthide)"},{value: "311", desc:"Eel (Dusthide)"},{value: "547", desc:"Facet (Dusthide)"},
{value: "298", desc:"Fissure (Dusthide)"},{value: "561", desc:"Foam (Dusthide)"},{value: "294", desc:"Freckle (Dusthide)"},{value: "522", desc:"Hawkmoth (Dusthide)"},
{value: "297", desc:"Hex (Dusthide)"},{value: "562", desc:"Hypnotic (Dusthide)"},{value: "299", desc:"Jester (Dusthide)"},{value: "316", desc:"Lacquer (Dusthide)"},
{value: "389", desc:"Larvae (Dusthide)"},{value: "405", desc:"Loam (Dusthide)"},{value: "309", desc:"Lode (Dusthide)"},{value: "306", desc:"Loop (Dusthide)"},
{value: "546", desc:"Malachite (Dusthide)"},{value: "559", desc:"Marbled (Dusthide)"},{value: "313", desc:"Marlin (Dusthide)"},{value: "556", desc:"Morph (Dusthide)"},
{value: "552", desc:"Mottle (Dusthide)"},{value: "305", desc:"Paint (Dusthide)"},{value: "548", desc:"Paisley (Dusthide)"},{value: "317", desc:"Parade (Dusthide)"},
{value: "301", desc:"Peregrine (Dusthide)"},{value: "550", desc:"Rosette (Dusthide)"},{value: "314", desc:"Safari (Dusthide)"},{value: "554", desc:"Sarcophagus (Dusthide)"},
{value: "300", desc:"Saturn (Dusthide)"},{value: "340", desc:"Seraph (Dusthide)"},{value: "551", desc:"Silkspot (Dusthide)"},{value: "558", desc:"Sludge (Dusthide)"},
{value: "315", desc:"Spinner (Dusthide)"},{value: "307", desc:"Spire (Dusthide)"},{value: "560", desc:"Striation (Dusthide)"},{value: "507", desc:"Tear (Dusthide)"},
{value: "555", desc:"Toxin (Dusthide)"},{value: "308", desc:"Trail (Dusthide)"},{value: "303", desc:"Weaver (Dusthide)"}],

"Everlux": [{value: "345", desc:"Arowana (Everlux)"},{value: "347", desc:"Blend (Everlux)"},{value: "359", desc:"Butterfly (Everlux)"},{value: "346", desc:"Choir (Everlux)"},
{value: "371", desc:"Coil (Everlux)"},{value: "372", desc:"Constellation (Everlux)"},{value: "378", desc:"Crown (Everlux)"},{value: "366", desc:"Current (Everlux)"},
{value: "348", desc:"Daub (Everlux)"},{value: "355", desc:"Edged (Everlux)"},{value: "349", desc:"Facet (Everlux)"},{value: "350", desc:"Flair (Everlux)"},
{value: "373", desc:"Foam (Everlux)"},{value: "369", desc:"Hawkmoth (Everlux)"},{value: "376", desc:"Lacquer (Everlux)"},{value: "351", desc:"Larvae (Everlux)"},
{value: "410", desc:"Loam (Everlux)"},{value: "360", desc:"Lode (Everlux)"},{value: "352", desc:"Malachite (Everlux)"},{value: "497", desc:"Marlin (Everlux)"},
{value: "362", desc:"Morph (Everlux)"},{value: "356", desc:"Mottle (Everlux)"},{value: "357", desc:"Noxtide (Everlux)"},{value: "361", desc:"Paint (Everlux)"},
{value: "510", desc:"Rosette (Everlux)"},{value: "363", desc:"Sarcophagus (Everlux)"},{value: "358", desc:"Saturn (Everlux)"},{value: "353", desc:"Seraph (Everlux)"},
{value: "354", desc:"Silkspot (Everlux)"},{value: "370", desc:"Sludge (Everlux)"},{value: "367", desc:"Spinner (Everlux)"},{value: "374", desc:"Stripes (Everlux)"},
{value: "364", desc:"Swallowtail (Everlux)"},{value: "508", desc:"Tear (Everlux)"},{value: "375", desc:"Toxin (Everlux)"},{value: "368", desc:"Trail (Everlux)"}],

"Cirrus": [{value: "429", desc:"Alloy (Cirrus)"},{value: "433", desc:"Bee (Cirrus)"},{value: "421", desc:"Blaze (Cirrus)"},{value: "422", desc:"Blend (Cirrus)"},
{value: "418", desc:"Carousel (Cirrus)"},{value: "420", desc:"Choir (Cirrus)"},{value: "432", desc:"Current (Cirrus)"},{value: "417", desc:"Daub (Cirrus)"}, 
{value: "426", desc:"Dye (Cirrus)"},{value: "423", desc:"Flair (Cirrus)"},{value: "434", desc:"Hypnotic (Cirrus)"},{value: "427", desc:"Jester (Cirrus)"},
{value: "435", desc:"Lacquer (Cirrus)"},{value: "438", desc:"Loam (Cirrus)"},{value: "416", desc:"Loop (Cirrus)"},{value: "496", desc:"Marlin (Cirrus)"},
{value: "430", desc:"Morph (Cirrus)"},{value: "424", desc:"Mottle (Cirrus)"},{value: "428", desc:"Paint (Cirrus)"},{value: "439", desc:"Roan (Cirrus)"},
{value: "415", desc:"Safari (Cirrus)"},{value: "419", desc:"Seraph (Cirrus)"},{value: "414", desc:"Silkspot (Cirrus)"},{value: "437", desc:"Spinner (Cirrus)"},
{value: "436", desc:"Stripes (Cirrus)"},{value: "431", desc:"Tear (Cirrus)"},{value: "425", desc:"Weaver (Cirrus)"}],

"Vigil": [{value: "533", desc:"Alloy (Vigil)"},{value: "511", desc:"Arowana (Vigil)"},{value: "525", desc:"Blaze (Vigil)"},{value: "529", desc:"Blend (Vigil)"},
{value: "515", desc:"Chess (Vigil)"},{value: "531", desc:"Clouded (Vigil)"},{value: "516", desc:"Coil (Vigil)"},{value: "540", desc:"Current (Vigil)"},
{value: "512", desc:"Daub (Vigil)"},{value: "536", desc:"Eel (Vigil)"},{value: "513", desc:"Eye Spots (Vigil)"},{value: "527", desc:"Hatch (Vigil)"},
{value: "542", desc:"Hypnotic (Vigil)"},{value: "544", desc:"Lacquer (Vigil)"},{value: "514", desc:"Larvae (Vigil)"},{value: "539", desc:"Marbled (Vigil)"},
{value: "537", desc:"Marlin (Vigil)"},{value: "532", desc:"Mottle (Vigil)"},{value: "534", desc:"Oxidize (Vigil)"},{value: "535", desc:"Paint (Vigil)"},
{value: "530", desc:"Rosette (Vigil)"},{value: "526", desc:"Silkspot (Vigil)"},{value: "538", desc:"Spinner (Vigil)"},{value: "543", desc:"Spire (Vigil)"},
{value: "541", desc:"Striation (Vigil)"},{value: "528", desc:"Warp (Vigil)"}],

"Thorntail": [{value: "458", desc:"Arowana (Thorntail)"},{value: "467", desc:"Blaze (Thorntail)"},{value: "469", desc:"Blend (Thorntail)"},{value: "475", desc:"Butterfly (Thorntail)"},
{value: "489", desc:"Chalice (Thorntail)"},{value: "466", desc:"Choir (Thorntail)"},{value: "463", desc:"Croc (Thorntail)"},{value: "481", desc:"Current (Thorntail)"},
{value: "460", desc:"Daub (Thorntail)"},{value: "480", desc:"Diamondback (Thorntail)"},{value: "491", desc:"Drip (Thorntail)"},{value: "471", desc:"Dye (Thorntail)"},
{value: "486", desc:"Foam (Thorntail)"},{value: "488", desc:"Hypnotic (Thorntail)"},{value: "487", desc:"Lacquer (Thorntail)"},{value: "484", desc:"Loam (Thorntail)"},
{value: "457", desc:"Loop (Thorntail)"},{value: "461", desc:"Lumen (Thorntail)"},{value: "482", desc:"Marlin (Thorntail)"},{value: "478", desc:"Morph (Thorntail)"},
{value: "473", desc:"Mottle (Thorntail)"},{value: "477", desc:"Paint (Thorntail)"},{value: "470", desc:"Paisley (Thorntail)"},{value: "472", desc:"Rosette (Thorntail)"},
{value: "462", desc:"Saddle (Thorntail)"},{value: "476", desc:"Sarcophagus (Thorntail)"},{value: "465", desc:"Seraph (Thorntail)"},{value: "490", desc:"Signal (Thorntail)"},
{value: "468", desc:"Silkspot (Thorntail)"},{value: "483", desc:"Spinner (Thorntail)"},{value: "485", desc:"Striation (Thorntail)"},{value: "464", desc:"Sugarplum (Thorntail)"},
{value: "479", desc:"Tear (Thorntail)"},{value: "459", desc:"Warp (Thorntail)"},{value: "474", desc:"Weaver (Thorntail)"}]};

//tertiary genes - sorted by modern and each ancient breed for easier insertions
const tertiaryGenes = {"Modern": [{value: "0", desc: "Basic"}, {value: "18", desc: "Capsule"},{value:"1", desc: "Circuit"},{value:"13", desc: "Contour"},
{value:"6", desc: "Crackle"},{value:"484", desc: "Darts"},{value:"421", desc: "Eclipse"},{value:"21", desc: "Filigree"},{value:"161", desc: "Firebreather"},
{value:"22", desc: "Firefly"},{value:"103", desc: "Flecks"},{value:"411", desc: "Gecko"},{value:"4", desc: "Gembond"},{value:"20", desc: "Ghost"},
{value:"10", desc: "Glimmer"},{value:"54", desc: "Glowtail"},{value:"53", desc: "Keel"},{value:"73", desc: "Koi"},
{value:"16", desc: "Lace"},{value:"584", desc: "Magpie"},{value:"9", desc: "Okapi"},{value:"17", desc: "Opal"},
{value:"24", desc: "Peacock"},{value:"107", desc: "Points"},{value:"168", desc: "Polkadot"},{value:"23", desc: "Ringlets"},
{value:"14", desc: "Runes"},{value:"15", desc: "Scales"},{value:"19", desc: "Smirch"},{value:"7", desc: "Smoke"},
{value:"105", desc: "Soap"},{value:"97", desc: "Sparkle"},{value:"8", desc: "Spines"},{value:"12", desc: "Stained"},
{value:"11", desc: "Thylacine"},{value:"5", desc: "Underbelly"},{value:"38", desc: "Veined"},{value:"213", desc: "Wish"}],

"Gaoler": [{value:"156", desc: "Angler (Gaoler)"}, {value:"36", desc: "Blossom (Gaoler)"}, {value:"55", desc: "Braids (Gaoler)"}, {value:"386", desc: "Branches (Gaoler)"},
{value:"75", desc: "Capsule (Gaoler)"}, {value:"166", desc: "Carnivore (Gaoler)"}, {value:"387", desc: "Circuit (Gaoler)"}, {value:"157", desc: "Contour (Gaoler)"},
{value:"265", desc: "Crystalline (Gaoler)"}, {value:"3", desc: "Fans (Gaoler)"}, {value:"303", desc: "Firebreather (Gaoler)"}, {value:"417", desc: "Gecko (Gaoler)"},
{value:"25", desc: "Ghost (Gaoler)"}, {value:"101", desc: "Glimmer (Gaoler)"}, {value:"27", desc: "Gnarlhorns (Gaoler)"}, {value:"592", desc: "Magpie (Gaoler)"},
{value:"37", desc: "Opal (Gaoler)"}, {value:"491", desc: "Ornaments (Gaoler)"}, {value:"77", desc: "Pinions (Gaoler)"}, {value:"30", desc: "Ringlets (Gaoler)"},
{value:"212", desc: "Riot (Gaoler)"}, {value:"32", desc: "Runes (Gaoler)"}, {value:"33", desc: "Scorpion (Gaoler)"}, {value:"26", desc: "Shardflank (Gaoler)"},
{value:"28", desc: "Smoke (Gaoler)"}, {value:"388", desc: "Soap (Gaoler)"}, {value:"99", desc: "Sparkle (Gaoler)"}, {value:"407", desc: "Spores (Gaoler)"},
{value:"71", desc: "Stained (Gaoler)"}, {value:"343", desc: "Starfall (Gaoler)"}, {value:"346", desc: "Thorns (Gaoler)"}, {value:"195", desc: "Thundercrack (Gaoler)"},
{value:"29", desc: "Thylacine (Gaoler)"}, {value:"542", desc: "Trickmurk (Gaoler)"}, {value:"31", desc: "Underbelly (Gaoler)"}, {value:"2", desc: "Veined (Gaoler)"},
{value:"35", desc: "Weathered (Gaoler)"}, {value:"389", desc: "Whiskers (Gaoler)"}, {value:"34", desc: "Wintercoat (Gaoler)"}],

"Banescale": [{value:"401", desc: "Blossom (Banescale)"}, {value:"310", desc: "Brightshine (Banescale)"}, {value:"74", desc: "Capsule (Banescale)"}, {value:"164", desc: "Carnivore (Banescale)"},
{value:"46", desc: "Contour (Banescale)"}, {value:"50", desc: "Crackle (Banescale)"}, {value:"41", desc: "Fans (Banescale)"}, {value:"43", desc: "Filigree (Banescale)"},
{value:"304", desc: "Firebreather (Banescale)"}, {value:"196", desc: "Flameforger (Banescale)"}, {value:"415", desc: "Gecko (Banescale)"}, {value:"47", desc: "Ghost (Banescale)"},
{value:"76", desc: "Gliders (Banescale)"}, {value:"95", desc: "Glimmer (Banescale)"}, {value:"44", desc: "Lace (Banescale)"}, {value:"588", desc: "Magpie (Banescale)"},
{value:"273", desc: "Mistral (Banescale)"}, {value:"158", desc: "Monarch (Banescale)"}, {value:"490", desc: "Ornaments (Banescale)"}, {value:"106", desc: "Peacock (Banescale)"},
{value:"51", desc: "Plumage (Banescale)"}, {value:"49", desc: "Porcupine (Banescale)"}, {value:"40", desc: "Ringlets (Banescale)"}, {value:"45", desc: "Skeletal (Banescale)"},
{value:"159", desc: "Soap (Banescale)"}, {value:"98", desc: "Sparkle (Banescale)"}, {value:"160", desc: "Spines (Banescale)"}, {value:"406", desc: "Spores (Banescale)"},
{value:"42", desc: "Squiggle (Banescale)"}, {value:"69", desc: "Stained (Banescale)"}, {value:"344", desc: "Thorns (Banescale)"}, {value:"476", desc: "Thundercrack (Banescale)"},
{value:"426", desc: "Trickmurk (Banescale)"}, {value:"39", desc: "Trimmings (Banescale)"}, {value:"52", desc: "Underbelly (Banescale)"}, {value:"313", desc: "Warrior (Banescale)"},
{value:"48", desc: "Wraith (Banescale)"}],

"Veilspun": [{value:"78", desc: "Angler (Veilspun)"}, {value:"65", desc: "Beetle (Veilspun)"}, {value:"396", desc: "Blossom (Veilspun)"}, {value:"63", desc: "Branches (Veilspun)"},
{value:"169", desc: "Brightshine (Veilspun)"}, {value:"56", desc: "Capsule (Veilspun)"}, {value:"167", desc: "Carnivore (Veilspun)"}, {value:"392", desc: "Contour (Veilspun)"},
{value:"58", desc: "Crackle (Veilspun)"}, {value:"66", desc: "Diaphanous (Veilspun)"}, {value:"423", desc: "Eclipse (Veilspun)"}, {value:"133", desc: "Filigree (Veilspun)"},
{value:"302", desc: "Firebreather (Veilspun)"}, {value:"61", desc: "Firefly (Veilspun)"}, {value:"64", desc: "Flecks (Veilspun)"}, {value:"420", desc: "Gecko (Veilspun)"},
{value:"131", desc: "Ghost (Veilspun)"}, {value:"102", desc: "Glimmer (Veilspun)"}, {value:"108", desc: "Koi (Veilspun)"}, {value:"596", desc: "Magpie (Veilspun)"},
{value:"393", desc: "Medusa (Veilspun)"}, {value:"544", desc: "Mistral (Veilspun)"}, {value:"67", desc: "Mop (Veilspun)"}, {value:"59", desc: "Okapi (Veilspun)"},
{value:"62", desc: "Opal (Veilspun)"}, {value:"488", desc: "Ornaments (Veilspun)"}, {value:"60", desc: "Peacock (Veilspun)"}, {value:"348", desc: "Riot (Veilspun)"},
{value:"57", desc: "Runes (Veilspun)"}, {value:"394", desc: "Smirch (Veilspun)"}, {value:"395", desc: "Soap (Veilspun)"}, {value:"100", desc: "Sparkle (Veilspun)"},
{value:"409", desc: "Spores (Veilspun)"}, {value:"72", desc: "Stained (Veilspun)"}, {value:"486", desc: "Starfall (Veilspun)"}, {value:"68", desc: "Thorns (Veilspun)"},
{value:"312", desc: "Thundercrack (Veilspun)"}, {value:"270", desc: "Trickmurk (Veilspun)"}, {value:"70", desc: "Underbelly (Veilspun)"}, {value:"134", desc: "Veined (Veilspun)"},
{value:"315", desc: "Warrior (Veilspun)"}],

"Aberration": [{value:"198", desc: "Augment (Aberration)"}, {value:"399", desc: "Blossom (Aberration)"}, {value:"199", desc: "Braids (Aberration)"}, {value:"612", desc: "Brightshine (Aberration)"},
{value:"83", desc: "Capsule (Aberration)"}, {value:"162", desc: "Carnivore (Aberration)"}, {value:"200", desc: "Contour (Aberration)"}, {value:"84", desc: "Fangs (Aberration)"},
{value:"201", desc: "Fans (Aberration)"}, {value:"202", desc: "Firebreather (Aberration)"}, {value:"85", desc: "Firefly (Aberration)"}, {value:"197", desc: "Flameforger (Aberration)"},
{value:"104", desc: "Flecks (Aberration)"}, {value:"86", desc: "Frills (Aberration)"}, {value:"412", desc: "Gecko (Aberration)"}, {value:"88", desc: "Ghost (Aberration)"},
{value:"94", desc: "Glimmer (Aberration)"}, {value:"89", desc: "Glowtail (Aberration)"}, {value:"87", desc: "Jewels (Aberration)"}, {value:"203", desc: "Koi (Aberration)"},
{value:"80", desc: "Kumo (Aberration)"}, {value:"585", desc: "Magpie (Aberration)"}, {value:"430", desc: "Medusa (Aberration)"}, {value:"81", desc: "Mucous (Aberration)"},
{value:"493", desc: "Ornaments (Aberration)"}, {value:"90", desc: "Peacock (Aberration)"}, {value:"79", desc: "Polkadot (Aberration)"}, {value:"82", desc: "Polypore (Aberration)"},
{value:"211", desc: "Riot (Aberration)"}, {value:"390", desc: "Rockbreaker (Aberration)"}, {value:"92", desc: "Scales (Aberration)"}, {value:"204", desc: "Skeletal (Aberration)"},
{value:"205", desc: "Smirch (Aberration)"}, {value:"96", desc: "Sparkle (Aberration)"}, {value:"206", desc: "Spines (Aberration)"}, {value:"404", desc: "Spores (Aberration)"},
{value:"207", desc: "Stained (Aberration)"}, {value:"485", desc: "Starfall (Aberration)"}, {value:"208", desc: "Thorns (Aberration)"}, {value:"311", desc: "Thundercrack (Aberration)"},
{value:"93", desc: "Thylacine (Aberration)"}, {value:"132", desc: "Underbelly (Aberration)"}, {value:"91", desc: "Veined (Aberration)"}],

"Undertide": [{value:"246", desc: "Angler (Undertide)"}, {value:"267", desc: "Blossom (Undertide)"}, {value:"248", desc: "Branches (Undertide)"}, {value:"170", desc: "Brightshine (Undertide)"},
{value:"111", desc: "Capsule (Undertide)"}, {value:"165", desc: "Carnivore (Undertide)"}, {value:"117", desc: "Circuit (Undertide)"}, {value:"249", desc: "Contour (Undertide)"},
{value:"115", desc: "Crackle (Undertide)"}, {value:"250", desc: "Crest (Undertide)"}, {value:"422", desc: "Eclipse (Undertide)"}, {value:"251", desc: "Fans (Undertide)"},
{value:"118", desc: "Featherbeard (Undertide)"}, {value:"116", desc: "Filigree (Undertide)"}, {value:"252", desc: "Firebreather (Undertide)"}, {value:"253", desc: "Firefly (Undertide)"},
{value:"112", desc: "Flecks (Undertide)"}, {value:"419", desc: "Gecko (Undertide)"}, {value:"123", desc: "Gembond (Undertide)"}, {value:"121", desc: "Ghost (Undertide)"},
{value:"464", desc: "Greenskeeper (Undertide)"}, {value:"269", desc: "Jellyfish (Undertide)"}, {value:"268", desc: "Keel (Undertide)"}, {value:"254", desc: "Koi (Undertide)"},
{value:"595", desc: "Magpie (Undertide)"}, {value:"255", desc: "Medusa (Undertide)"}, {value:"272", desc: "Mistral (Undertide)"}, {value:"126", desc: "Nudibranch (Undertide)"},
{value:"129", desc: "Okapi (Undertide)"}, {value:"247", desc: "Opal (Undertide)"}, {value:"489", desc: "Ornaments (Undertide)"}, {value:"128", desc: "Plating (Undertide)"},
{value:"256", desc: "Porcupine (Undertide)"}, {value:"127", desc: "Pufferfish (Undertide)"}, {value:"119", desc: "Remora (Undertide)"}, {value:"120", desc: "Ringlets (Undertide)"},
{value:"114", desc: "Runes (Undertide)"}, {value:"130", desc: "Sailfin (Undertide)"}, {value:"257", desc: "Scales (Undertide)"}, {value:"258", desc: "Shark (Undertide)"},
{value:"259", desc: "Smirch (Undertide)"}, {value:"260", desc: "Smoke (Undertide)"}, {value:"124", desc: "Soap (Undertide)"}, {value:"122", desc: "Sparkle (Undertide)"},
{value:"261", desc: "Spines (Undertide)"}, {value:"481", desc: "Spores (Undertide)"}, {value:"110", desc: "Stained (Undertide)"}, {value:"262", desc: "Stinger (Undertide)"},
{value:"125", desc: "Tentacles (Undertide)"}, {value:"263", desc: "Thorns (Undertide)"}, {value:"264", desc: "Topcoat (Undertide)"}, {value:"427", desc: "Trickmurk (Undertide)"},
{value:"109", desc: "Underbelly (Undertide)"}, {value:"113", desc: "Veined (Undertide)"}, {value:"301", desc: "Wavecrest (Undertide)"}],

"Aether": [{value:"316", desc: "Angler (Aether)"}, {value:"336", desc: "Blossom (Aether)"}, {value:"317", desc: "Braids (Aether)"}, {value:"318", desc: "Branches (Aether)"},
{value:"319", desc: "Capsule (Aether)"}, {value:"163", desc: "Carnivore (Aether)"}, {value:"135", desc: "Circuit (Aether)"}, {value:"136", desc: "Contour (Aether)"},
{value:"320", desc: "Crackle (Aether)"}, {value:"424", desc: "Crystalline (Aether)"}, {value:"321", desc: "Diaphanous (Aether)"}, {value:"322", desc: "Fans (Aether)"},
{value:"306", desc: "Firebreather (Aether)"}, {value:"328", desc: "Firefly (Aether)"}, {value:"337", desc: "Fishbone (Aether)"}, {value:"340", desc: "Flameforger (Aether)"},
{value:"323", desc: "Flecks (Aether)"}, {value:"141", desc: "Flutter (Aether)"}, {value:"413", desc: "Gecko (Aether)"}, {value:"137", desc: "Gembond (Aether)"},
{value:"324", desc: "Ghost (Aether)"}, {value:"138", desc: "Glowtail (Aether)"}, {value:"139", desc: "Keel (Aether)"}, {value:"325", desc: "Koi (Aether)"},
{value:"142", desc: "Lace (Aether)"}, {value:"586", desc: "Magpie (Aether)"}, {value:"143", desc: "Mandibles (Aether)"}, {value:"326", desc: "Medusa (Aether)"},
{value:"428", desc: "Mistral (Aether)"}, {value:"140", desc: "Monarch (Aether)"}, {value:"327", desc: "Nudibranch (Aether)"}, {value:"329", desc: "Ornaments (Aether)"},
{value:"146", desc: "Points (Aether)"}, {value:"330", desc: "Porcupine (Aether)"}, {value:"331", desc: "Sailfin (Aether)"}, {value:"147", desc: "Scales (Aether)"},
{value:"150", desc: "Smirch (Aether)"}, {value:"151", desc: "Smoke (Aether)"}, {value:"338", desc: "Soap (Aether)"}, {value:"149", desc: "Space (Aether)"},
{value:"152", desc: "Sparkle (Aether)"}, {value:"153", desc: "Spines (Aether)"}, {value:"332", desc: "Spores (Aether)"}, {value:"145", desc: "Stained (Aether)"},
{value:"209", desc: "Starfall (Aether)"}, {value:"148", desc: "Stinger (Aether)"}, {value:"339", desc: "Tentacles (Aether)"}, {value:"333", desc: "Thorns (Aether)"},
{value:"334", desc: "Thylacine (Aether)"}, {value:"271", desc: "Trickmurk (Aether)"}, {value:"144", desc: "Underbelly (Aether)"}, {value:"335", desc: "Veined (Aether)"},
{value:"583", desc: "Wavecrest (Aether)"}, {value:"154", desc: "Whiskers (Aether)"}, {value:"155", desc: "Wish (Aether)"}],

"Sandsurge": [{value:"173", desc: "Augment (Sandsurge)"}, {value:"470", desc: "Batty (Sandsurge)"}, {value:"174", desc: "Beard (Sandsurge)"}, {value:"398", desc: "Blossom (Sandsurge)"},
{value:"189", desc: "Branches (Sandsurge)"}, {value:"410", desc: "Capsule (Sandsurge)"}, {value:"403", desc: "Carnivore (Sandsurge)"}, {value:"183", desc: "Chitin (Sandsurge)"},
{value:"184", desc: "Crest (Sandsurge)"}, {value:"177", desc: "Darts (Sandsurge)"}, {value:"472", desc: "Eclipse (Sandsurge)"}, {value:"305", desc: "Firebreather (Sandsurge)"},
{value:"473", desc: "Firefly (Sandsurge)"}, {value:"185", desc: "Fishbone (Sandsurge)"}, {value:"341", desc: "Flameforger (Sandsurge)"}, {value:"474", desc: "Flecks (Sandsurge)"},
{value:"418", desc: "Gecko (Sandsurge)"}, {value:"176", desc: "Gembond (Sandsurge)"}, {value:"467", desc: "Gnarlhorns (Sandsurge)"}, {value:"186", desc: "Keel (Sandsurge)"},
{value:"175", desc: "Kumo (Sandsurge)"}, {value:"187", desc: "Lace (Sandsurge)"}, {value:"593", desc: "Magpie (Sandsurge)"}, {value:"471", desc: "Mandibles (Sandsurge)"},
{value:"182", desc: "Okapi (Sandsurge)"}, {value:"191", desc: "Peacock (Sandsurge)"}, {value:"475", desc: "Polkadot (Sandsurge)"}, {value:"497", desc: "Riot (Sandsurge)"},
{value:"245", desc: "Rockbreaker (Sandsurge)"}, {value:"178", desc: "Runes (Sandsurge)"}, {value:"190", desc: "Shark (Sandsurge)"}, {value:"192", desc: "Smirch (Sandsurge)"},
{value:"469", desc: "Smoke (Sandsurge)"}, {value:"180", desc: "Soap (Sandsurge)"}, {value:"193", desc: "Sparkle (Sandsurge)"}, {value:"188", desc: "Spectre (Sandsurge)"},
{value:"181", desc: "Spines (Sandsurge)"}, {value:"408", desc: "Spores (Sandsurge)"}, {value:"172", desc: "Stained (Sandsurge)"}, {value:"210", desc: "Starfall (Sandsurge)"},
{value:"347", desc: "Thorns (Sandsurge)"}, {value:"194", desc: "Thundercrack (Sandsurge)"}, {value:"179", desc: "Thylacine (Sandsurge)"}, {value:"171", desc: "Underbelly (Sandsurge)"},
{value:"314", desc: "Warrior (Sandsurge)"}, {value:"468", desc: "Whiskers (Sandsurge)"}],

"Auraboa": [{value:"535", desc: "Angler (Auraboa)"}, {value:"214", desc: "Batty (Auraboa)"}, {value:"400", desc: "Blossom (Auraboa)"},
{value:"217", desc: "Branches (Auraboa)"}, {value:"229", desc: "Capsule (Auraboa)"}, {value:"402", desc: "Chitin (Auraboa)"}, {value:"230", desc: "Contour (Auraboa)"},
{value:"231", desc: "Crackle (Auraboa)"}, {value:"215", desc: "Crest (Auraboa)"}, {value:"266", desc: "Crystalline (Auraboa)"}, {value:"536", desc: "Eclipse (Auraboa)"}, {value:"233", desc: "Firebreather (Auraboa)"}, {value:"232", desc: "Firefly (Auraboa)"}, {value:"216", desc: "Fishbone (Auraboa)"},
{value:"414", desc: "Gecko (Auraboa)"}, {value:"308", desc: "Greenskeeper (Auraboa)"}, {value:"234", desc: "Keel (Auraboa)"}, {value:"235", desc: "Koi (Auraboa)"},
{value:"587", desc: "Magpie (Auraboa)"}, {value:"218", desc: "Medusa (Auraboa)"}, {value:"236", desc: "Opal (Auraboa)"}, {value:"495", desc: "Ornaments (Auraboa)"},
{value:"219", desc: "Paradise (Auraboa)"}, {value:"237", desc: "Peacock (Auraboa)"}, {value:"220", desc: "Plumage (Auraboa)"}, {value:"238", desc: "Polkadot (Auraboa)"},
{value:"221", desc: "Porcupine (Auraboa)"}, {value:"244", desc: "Rockbreaker (Auraboa)"}, {value:"222", desc: "Sailfin (Auraboa)"}, {value:"239", desc: "Scales (Auraboa)"},
{value:"223", desc: "Skuttle (Auraboa)"}, {value:"240", desc: "Smoke (Auraboa)"}, {value:"241", desc: "Spines (Auraboa)"}, {value:"405", desc: "Spores (Auraboa)"},
{value:"242", desc: "Stained (Auraboa)"}, {value:"342", desc: "Starfall (Auraboa)"}, {value:"224", desc: "Stinger (Auraboa)"}, {value:"225", desc: "Terracotta (Auraboa)"},
{value:"226", desc: "Thorns (Auraboa)"}, {value:"243", desc: "Topcoat (Auraboa)"}, {value:"228", desc: "Underbelly (Auraboa)"}, {value:"478", desc: "Warrior (Auraboa)"},
{value:"431", desc: "Wavecrest (Auraboa)"}, {value:"537", desc: "Whiskers (Auraboa)"}, {value:"227", desc: "Willow (Auraboa)"}],

"Dusthide": [{value:"615", desc: "Agate (Dusthide)"}, {value:"286", desc: "Angler (Dusthide)"}, {value:"276", desc: "Antlers (Dusthide)"}, {value:"598", desc: "Armor (Dusthide)"},
{value:"280", desc: "Augment (Dusthide)"}, {value:"289", desc: "Batty (Dusthide)"}, {value:"599", desc: "Beetle (Dusthide)"}, {value:"281", desc: "Blossom (Dusthide)"},
{value:"309", desc: "Brightshine (Dusthide)"}, {value:"600", desc: "Capsule (Dusthide)"}, {value:"282", desc: "Carnivore (Dusthide)"},{value:"601", desc: "Chitin (Dusthide)"},
{value:"602", desc: "Coral (Dusthide)"}, {value:"288", desc: "Dewlap (Dusthide)"}, {value:"603", desc: "Eclipse (Dusthide)"}, {value:"277", desc: "Fishbone (Dusthide)"},
{value:"483", desc: "Flameforger (Dusthide)"}, {value:"616", desc: "Flutter (Dusthide)"}, {value:"416", desc: "Gecko (Dusthide)"}, {value:"287", desc: "Gembond (Dusthide)"},
{value:"278", desc: "Ghost (Dusthide)"}, {value:"279", desc: "Glowtail (Dusthide)"}, {value:"307", desc: "Greenskeeper (Dusthide)"}, {value:"604", desc: "Koi (Dusthide)"},
{value:"605", desc: "Lace (Dusthide)"}, {value:"590", desc: "Magpie (Dusthide)"}, {value:"283", desc: "Mandibles (Dusthide)"}, {value:"284", desc: "Okapi (Dusthide)"},
{value:"285", desc: "Opal (Dusthide)"}, {value:"492", desc: "Ornaments (Dusthide)"}, {value:"290", desc: "Pachy (Dusthide)"}, {value:"614", desc: "Paradise (Dusthide)"},
{value:"293", desc: "Polkadot (Dusthide)"}, {value:"294", desc: "Ringlets (Dusthide)"}, {value:"349", desc: "Riot (Dusthide)"}, {value:"533", desc: "Rockbreaker (Dusthide)"},
{value:"606", desc: "Skuttle (Dusthide)"}, {value:"297", desc: "Smoke (Dusthide)"}, {value:"292", desc: "Sparkle (Dusthide)"}, {value:"607", desc: "Spectre (Dusthide)"},
{value:"298", desc: "Spines (Dusthide)"}, {value:"295", desc: "Spores (Dusthide)"}, {value:"274", desc: "Stained (Dusthide)"}, {value:"608", desc: "Tentacles (Dusthide)"},
{value:"345", desc: "Thorns (Dusthide)"}, {value:"609", desc: "Thylacine (Dusthide)"}, {value:"299", desc: "Topcoat (Dusthide)"}, {value:"275", desc: "Underbelly (Dusthide)"},
{value:"296", desc: "Veil (Dusthide)"}, {value:"480", desc: "Warrior (Dusthide)"}, {value:"300", desc: "Wavecrest (Dusthide)"}, {value:"617", desc: "Weathered (Dusthide)"},
{value:"291", desc: "Whiskers (Dusthide)"}, {value:"618", desc: "Wool (Dusthide)"}],

"Everlux": [{value:"350", desc: "Augment (Everlux)"}, {value:"351", desc: "Batty (Everlux)"}, {value:"465", desc: "Brightshine (Everlux)"}, {value:"352", desc: "Chitin (Everlux)"},
{value:"425", desc: "Crystalline (Everlux)"}, {value:"353", desc: "Eclipse (Everlux)"}, {value:"361", desc: "Eclosion (Everlux)"}, {value:"354", desc: "Fishbone (Everlux)"},
{value:"355", desc: "Flutter (Everlux)"}, {value:"359", desc: "Gecko (Everlux)"}, {value:"362", desc: "Gembond (Everlux)"}, {value:"360", desc: "Gliders (Everlux)"},
{value:"356", desc: "Glitch (Everlux)"}, {value:"385", desc: "Harp (Everlux)"}, {value:"363", desc: "Jellyfish (Everlux)"}, {value:"364", desc: "Kumo (Everlux)"},
{value:"591", desc: "Magpie (Everlux)"}, {value:"365", desc: "Mandibles (Everlux)"}, {value:"429", desc: "Mistral (Everlux)"}, {value:"366", desc: "Nudibranch (Everlux)"},
{value:"494", desc: "Ornaments (Everlux)"}, {value:"367", desc: "Paradise (Everlux)"}, {value:"368", desc: "Peacock (Everlux)"}, {value:"369", desc: "Points (Everlux)"},
{value:"370", desc: "Polkadot (Everlux)"}, {value:"371", desc: "Rift (Everlux)"}, {value:"496", desc: "Riot (Everlux)"}, {value:"391", desc: "Rockbreaker (Everlux)"},
{value:"372", desc: "Runes (Everlux)"}, {value:"373", desc: "Scales (Everlux)"}, {value:"374", desc: "Skuttle (Everlux)"}, {value:"375", desc: "Smoke (Everlux)"},
{value:"376", desc: "Space (Everlux)"}, {value:"377", desc: "Sparkle (Everlux)"}, {value:"378", desc: "Spines (Everlux)"}, {value:"379", desc: "Spores (Everlux)"},
{value:"357", desc: "Stained (Everlux)"}, {value:"380", desc: "Sunsail (Everlux)"}, {value:"381", desc: "Thorns (Everlux)"}, {value:"358", desc: "Underbelly (Everlux)"},
{value:"432", desc: "Wavecrest (Everlux)"}, {value:"382", desc: "Whiskers (Everlux)"}, {value:"383", desc: "Wish (Everlux)"}, {value:"384", desc: "Wool (Everlux)"}],

"Cirrus": [{value:"435", desc: "Blossom (Cirrus)"}, {value:"436", desc: "Braids (Cirrus)"}, {value:"466", desc: "Brightshine (Cirrus)"}, {value:"437", desc: "Coral (Cirrus)"},
{value:"438", desc: "Crackle (Cirrus)"}, {value:"538", desc: "Crystalline (Cirrus)"}, {value:"440", desc: "Deco (Cirrus)"}, {value:"439", desc: "Eclipse (Cirrus)"},
{value:"482", desc: "Flameforger (Cirrus)"}, {value:"441", desc: "Flames (Cirrus)"}, {value:"442", desc: "Ghost (Cirrus)"}, {value:"443", desc: "Glitch (Cirrus)"},
{value:"444", desc: "Gnarlhorns (Cirrus)"}, {value:"463", desc: "Greenskeeper (Cirrus)"}, {value:"445", desc: "Kumo (Cirrus)"}, {value:"589", desc: "Magpie (Cirrus)"},
{value:"446", desc: "Medusa (Cirrus)"}, {value:"448", desc: "Mist (Cirrus)"}, {value:"447", desc: "Okapi (Cirrus)"}, {value:"487", desc: "Ornaments (Cirrus)"},
{value:"449", desc: "Paradise (Cirrus)"}, {value:"450", desc: "Peacock (Cirrus)"}, {value:"451", desc: "Polypore (Cirrus)"}, {value:"460", desc: "Quagga (Cirrus)"},
{value:"462", desc: "Runes (Cirrus)"}, {value:"452", desc: "Sailfin (Cirrus)"}, {value:"433", desc: "Scales (Cirrus)"}, {value:"453", desc: "Skeletal (Cirrus)"},
{value:"461", desc: "Sparkle (Cirrus)"}, {value:"454", desc: "Spectre (Cirrus)"}, {value:"459", desc: "Spores (Cirrus)"}, {value:"455", desc: "Thorns (Cirrus)"},
{value:"477", desc: "Thundercrack (Cirrus)"}, {value:"456", desc: "Topscale (Cirrus)"}, {value:"434", desc: "Underbelly (Cirrus)"}, {value:"479", desc: "Warrior (Cirrus)"},
{value:"457", desc: "Willow (Cirrus)"}, {value:"458", desc: "Wool (Cirrus)"}],

"Vigil": [{value:"547", desc: "Agate (Vigil)"}, {value:"551", desc: "Barnacle (Vigil)"}, {value:"567", desc: "Belfry (Vigil)"}, {value:"548", desc: "Branches (Vigil)"},
{value:"613", desc: "Brightshine (Vigil)"}, {value:"553", desc: "Candlelight (Vigil)"}, {value:"545", desc: "Capsule (Vigil)"}, {value:"549", desc: "Carnivore (Vigil)"},
{value:"552", desc: "Coral (Vigil)"}, {value:"554", desc: "Crest (Vigil)"}, {value:"555", desc: "Deco (Vigil)"}, {value:"556", desc: "Dewlap (Vigil)"},
{value:"557", desc: "Eclipse (Vigil)"}, {value:"568", desc: "Fangs (Vigil)"}, {value:"559", desc: "Firebreather (Vigil)"}, {value:"560", desc: "Gecko (Vigil)"},
{value:"561", desc: "Ghost (Vigil)"}, {value:"558", desc: "Glitch (Vigil)"}, {value:"562", desc: "Gnarlhorns (Vigil)"}, {value:"611", desc: "Greenskeeper (Vigil)"},
{value:"563", desc: "Kumo (Vigil)"}, {value:"597", desc: "Magpie (Vigil)"}, {value:"564", desc: "Mandibles (Vigil)"}, {value:"565", desc: "Medusa (Vigil)"},
{value:"566", desc: "Overgrow (Vigil)"}, {value:"569", desc: "Plating (Vigil)"}, {value:"570", desc: "Plumage (Vigil)"}, {value:"571", desc: "Polkadot (Vigil)"},
{value:"572", desc: "Porcelain (Vigil)"}, {value:"573", desc: "Quagga (Vigil)"}, {value:"574", desc: "Rift (Vigil)"}, {value:"550", desc: "Rooster (Vigil)"},
{value:"580", desc: "Smirch (Vigil)"}, {value:"575", desc: "Tentacles (Vigil)"},{value:"576", desc: "Thorns (Vigil)"}, {value:"546", desc: "Underbelly (Vigil)"}, 
{value:"579", desc: "Veined (Vigil)"}, {value:"582", desc: "Wavecrest (Vigil)"}, {value:"577", desc: "Webmane (Vigil)"}, {value:"578", desc: "Willow (Vigil)"},
{value:"581", desc: "Wish (Vigil)"}], 

"Thorntail": [{value:"498", desc: "Angler (Thorntail)"}, {value:"499", desc: "Beetle (Thorntail)"}, {value:"500", desc: "Blossom (Thorntail)"}, {value:"501", desc: "Coral (Thorntail)"}, {value:"502", desc: "Crackle (Thorntail)"},
{value:"539", desc: "Crystalline (Thorntail)"}, {value:"503", desc: "Dewlap (Thorntail)"}, {value:"504", desc: "Diaphanous (Thorntail)"}, {value:"505", desc: "Fishbone (Thorntail)"},
{value:"506", desc: "Flames (Thorntail)"}, {value:"507", desc: "Flutter (Thorntail)"}, {value:"508", desc: "Gecko (Thorntail)"}, {value:"509", desc: "Ghost (Thorntail)"},
{value:"510", desc: "Glitch (Thorntail)"}, {value:"610", desc: "Greenskeeper (Thorntail)"}, {value:"511", desc: "Hornet (Thorntail)"}, {value:"512", desc: "Kumo (Thorntail)"},
{value:"594", desc: "Magpie (Thorntail)"}, {value:"513", desc: "Mandibles (Thorntail)"}, {value:"514", desc: "Medusa (Thorntail)"}, {value:"543", desc: "Mistral (Thorntail)"},
{value:"515", desc: "Monarch (Thorntail)"}, {value:"516", desc: "Moss (Thorntail)"}, {value:"517", desc: "Paradise (Thorntail)"}, {value:"518", desc: "Peacock (Thorntail)"},
{value:"519", desc: "Polkadot (Thorntail)"}, {value:"534", desc: "Rockbreaker (Thorntail)"}, {value:"520", desc: "Runes (Thorntail)"}, {value:"521", desc: "Sailfin (Thorntail)"},
{value:"522", desc: "Skeletal (Thorntail)"}, {value:"523", desc: "Space (Thorntail)"}, {value:"524", desc: "Spectre (Thorntail)"}, {value:"525", desc: "Spines (Thorntail)"},
{value:"526", desc: "Stained (Thorntail)"}, {value:"540", desc: "Sweet (Thorntail)"}, {value:"527", desc: "Tentacles (Thorntail)"}, {value:"541", desc: "Trickmurk (Thorntail)"},
{value:"528", desc: "Tusked (Thorntail)"}, {value:"529", desc: "Underbelly (Thorntail)"}, {value:"530", desc: "Wish (Thorntail)"}, {value:"531", desc: "Wool (Thorntail)"},
{value:"532", desc: "Yarn (Thorntail)"}]};

const colours = {"Maize": "#FFFDEA", "Cream": "#FFEFDC", "Antique": " #D8D6CD", "White": "#FFFFFF", "Moon": "#D8D7D8", "Ice": "#EBEFFF", "Orca": "#E0DFFF",
    "Platinum": "#C8BECE", "Silver": "#BBBABF", "Dust": "#9C9C9E", "Grey": "#808080", "Smoke": "#9494A9", "Gloom": "#535264",
    "Lead": "#413C3F", "Shale": "#4D4850", "Flint": "#626268", "Charcoal": "#545454", "Coal": "#4B4946", "Oilslick": "#342B25",
    "Black": "#333333", "Obsidian": "#1D2224", "Eldritch": "#252A25", "Midnight": "#252735", "Shadow": "#3A2E44", "Blackberry": "#4B294F",
    "Mulberry": "#6F235D", "Plum": "#853390", "Wisteria": "#724F7B", "Thistle": "#8F7C8B", "Fog": "#A593B0", "Mist": "#E1CEFF",
    "Lavender": "#CCA4E0", "Heather": "#9777BD", "Purple": "#A261CF", "Orchid": "#D950FF", "Amethyst": "#993BD0", "Nightshade": "#782EB2",
    "Violet": "#643F9C", "Grape": "#570FC0", "Royal": "#4D2C89", "Eggplant": "#332B65", "Iris": "#535195", "Storm": "#757ADB",
    "Twilight": "#474AA0", "Indigo": "#2D237A", "Sapphire": "#0D095B", "Navy": "#212B5F", "Cobalt": "#003484", "Ultramarine": "#1C51E7",
    "Blue": "#324BA9", "Periwinkle": "#4866D5", "Lapis": "#2B84FF", "Splash": "#6392DF", "Cornflower": "#75A8FF", "Sky": "#AEC8FF",
    "Stonewash": "#7895C1", "Overcast": "#444F69", "Steel": "#556979", "Denim": "#2F4557", "Abyss": "#0D1E24", "Phthalo": "#0B2D46",
    "Azure": "#0A3D67", "Caribbean": "#0086CE", "Teal": "#2B768F", "Cerulean": "#00B4D6", "Cyan": "#00FFF0", "Robin": "#9AEAEF", "Aqua": "#72C4C4",
    "Turquoise": "#3AA0A1", "Spruce": "#8BBBB2", "Pistachio": "#E2FFE6", "Seafoam": "#B2E2BD", "Mint": "#9AFFC7", "Jade": "#61AB89", "Spearmint": "#148F67",
    "Thicket": "#005F48", "Peacock": "#20603F", "Emerald": "#21613F", "Shamrock": "#236925", "Jungle": "#1F361A", "Hunter": "#1D2715", 
    "Forest": "#425035", "Camo": "#51684C", "Algae": "#97AF8B", "Swamp": "#687F67", "Avocado": "#567C34", "Green": "#629C3F", "Fern": "#7ECE73", "Mantis": "#99FF9C",
    "Pear": "#8ECD55", "Leaf": "#A5E32D", "Radioactive": "#C6FF00", "Honeydew": "#D0E672", "Peridot": "#E8FFB5", "Chartreuse": "#B4CD3C",
    "Spring": "#A9A832", "Crocodile": "#828335", "Olive": "#697135", "Murk": "#4B4420", "Moss": "#7F7745", "Goldenrod": "#BEA55D", "Amber": "#C18E1B",
    "Honey": "#D1B300", "Lemon": "#FFE63B", "Yellow": "#F9E255", "Grapefruit": "#F7FF6F", "Banana": "#FFEC80", "Sanddollar": "#EBE7AE", "Flaxen": "#FDE9AE",
    "Ivory": "#FFD297", "Buttercup": "#F6BF6B", "Gold": "#E8AF49", "Metals": "#D1B046", "Marigold": "#FFB43B", "Sunshine": "#FA912B", "Saffron": "#FF8400",
    "Sunset": "#FFA248", "Peach": "#FFB576", "Cantaloupe": "#FF984F", "Orange": "#D5602B", "Bronze": "#B2560D", "Terracotta": "#B23B07", "Carrot": "#FF5500",
    "Fire": "#EF5C23", "Pumpkin": "#FF6840", "Tangerine": "#FF7360", "Cinnamon": "#C05A39", "Caramel": "#C67047", "Sand": "#B27749", "Tan": "#C49A70",
    "Beige": "#CABBA2", "Stone": "#827A64", "Taupe": "#6D665A", "Slate": "#564D48", "Driftwood": "#766359", "Latte": "#977B6C", "Dirt": "#76483F", "Clay": "#603F3D",
    "Sable": "#57372C", "Umber": "#2F1E1A", "Soil": "#5A4534", "Hickory": "#725639", "Tarnish": "#855C32", "Ginger": "#90532B", "Brown": "#8F5B3F", "Chocolate": "#563012",
    "Auburn": "#7B3C1D", "Copper": "#A44B28", "Rust": "#8B3220", "Tomato": "#BA311C", "Vermilion": "#E22D17", "Ruby": "#CD000E", "Cherry": "#AA0024", "Crimson": "#850012",
    "Garnet": "#5B0F14", "Sanguine": "#2F0002", "Blood": "#451717", "Maroon": "#652127", "Berry": "#8B272C", "Red": "#C1272D", "Strawberry": "#DE3235", "Cerise": "#A22929",
    "Carmine": "#B13A3A", "Brick": "#9A534D", "Coral": "#CC6F6F", "Blush": "#FFA2A2", "Cottoncandy": "#EB7997", "Watermelon": "#DB518D",
    "Magenta": "#E934AA", "Fuchsia": "#EC0089", "Raspberry": "#8A0249", "Wine": "#4D0F28", "Mauve": "#9C4875", "Pink": "#E77FBF", "Bubblegum": "#EAA9FF", "Rose": "#FFD6F6", "Pearl": "#FBE9F8"};

const eyes = {"Common": "0", "Uncommon": "1", "Unusual": "2", "Rare": "3", "Faceted": "4", "Multi-Gaze": "5", "Primal": "6", "Glowing": "7", "Dark Sclera": "8",
      "Goat": "9", "Swirl": "10", "Innocent": "11", "Pastel": "12", "Bright": "13", "Button": "14", "Faded": "15", "Dark": "16"};

const clan = {"Earth": "1", "Plague": "2", "Wind": "3", "Water": "4", "Lightning" : "5", "Ice": "6",
          "Shadow": "7", "Light": "8", "Arcane": "9", "Nature": "10", "Fire": "11"};